import type { Puzzle } from '../chess-data'

export const PUZZLES: Puzzle[] = [
  // === EASY PUZZLES (Rating 400-600) ===
  {
    id: 'p1',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    moves: ['Qxf7#'],
    rating: 400,
    themes: ['mate', 'scholarsMate'],
    title: "Scholar's Mate",
    description: 'Find the checkmate in one move!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p2',
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2',
    moves: ['Qh4#'],
    rating: 400,
    themes: ['mate', 'foolsMate'],
    title: "Fool's Mate",
    description: 'White has weakened the kingside terribly!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p3',
    fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    moves: ['Re8#'],
    rating: 450,
    themes: ['mate', 'backRank'],
    title: 'Back Rank Mate',
    description: 'The king is trapped. Find checkmate!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p4',
    fen: '7k/8/6K1/8/8/8/8/Q7 w - - 0 1',
    moves: ['Qa8#'],
    rating: 450,
    themes: ['mate', 'queenMate'],
    title: 'Queen Checkmate',
    description: 'Deliver checkmate with queen support.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p5',
    fen: '7k/R7/6K1/8/8/8/8/8 w - - 0 1',
    moves: ['Ra8#'],
    rating: 450,
    themes: ['mate', 'rookMate'],
    title: 'Rook Checkmate',
    description: 'Deliver checkmate with rook support.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p6',
    fen: '6k1/5ppp/8/8/8/8/5PPP/R3R1K1 w - - 0 1',
    moves: ['Re8#'],
    rating: 500,
    themes: ['mate', 'backRank'],
    title: 'Double Rook Power',
    description: 'Deliver the back rank mate!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p7',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    moves: ['Ng5'],
    rating: 550,
    themes: ['attack', 'threat'],
    title: 'Attack f7',
    description: 'Threaten the weak f7 pawn.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p8',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    moves: ['Bc4'],
    rating: 550,
    themes: ['development', 'opening'],
    title: 'Italian Opening',
    description: 'Find the best developing move.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p9',
    fen: '6rk/6pp/8/6N1/8/8/8/6K1 w - - 0 1',
    moves: ['Nf7#'],
    rating: 500,
    themes: ['mate', 'smotheredMate'],
    title: 'Smothered Mate',
    description: 'Deliver checkmate with the knight!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p10',
    fen: '6k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1',
    moves: ['Qd8#'],
    rating: 550,
    themes: ['mate', 'backRank'],
    title: 'Back Rank Strike',
    description: 'The king is trapped behind its own pawns!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p11',
    fen: 'rnbqkbnr/ppp2ppp/8/3pp3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq d6 0 3',
    moves: ['Nxe5'],
    rating: 600,
    themes: ['tactic', 'capture'],
    title: 'Free Pawn',
    description: 'Capture the undefended pawn.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p12',
    fen: 'r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3',
    moves: ['a6'],
    rating: 600,
    themes: ['defense', 'kickBishop'],
    title: 'Kick the Bishop',
    description: 'Challenge Whites strong bishop.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p13',
    fen: '4k3/8/8/8/8/3R4/8/4K3 w - - 0 1',
    moves: ['Rd8+'],
    rating: 500,
    themes: ['tactic', 'check'],
    title: 'Rook Check',
    description: 'Give check to improve position.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p14',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    moves: ['Ng5', 'd5', 'exd5'],
    rating: 600,
    themes: ['attack', 'opening'],
    title: 'Fried Liver Setup',
    description: 'Begin the famous attack!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p15',
    fen: 'rnbqkb1r/pppppppp/5n2/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 1 2',
    moves: ['e5'],
    rating: 550,
    themes: ['opening', 'space'],
    title: 'Gain Space',
    description: 'Push the pawn to attack.',
    difficulty: 'easy',
    xpReward: 10,
  },
  // === MEDIUM PUZZLES (Rating 700-950) ===
  {
    id: 'p16',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 5',
    moves: ['Bg5', 'h6', 'Bh4'],
    rating: 750,
    themes: ['pin', 'pressure'],
    title: 'Pin the Knight',
    description: 'Use a pin to apply pressure.',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p17',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 5',
    moves: ['O-O', 'O-O', 'Nc3'],
    rating: 750,
    themes: ['development', 'castling'],
    title: 'Castle and Develop',
    description: 'Get king to safety.',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p18',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 4 4',
    moves: ['Nxe5', 'Nxe5', 'd4'],
    rating: 800,
    themes: ['tactic', 'fork'],
    title: 'Fork Trick',
    description: 'Win a pawn tactically.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p19',
    fen: 'rnbqkb1r/pppp1ppp/5n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    moves: ['d3', 'd6', 'Bg5'],
    rating: 800,
    themes: ['opening', 'development'],
    title: 'Italian Game',
    description: 'Build up pressure.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p20',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    moves: ['Qf7#'],
    rating: 700,
    themes: ['mate', 'tactics'],
    title: 'Quick Strike',
    description: 'Find the instant checkmate!',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p21',
    fen: 'rnbqkb1r/ppp2ppp/3p1n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    moves: ['d4', 'exd4', 'Nxd4'],
    rating: 850,
    themes: ['center', 'pawnBreak'],
    title: 'Central Break',
    description: 'Open up the center.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p22',
    fen: 'rnbqkb1r/ppp2ppp/3p1n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    moves: ['Nc3', 'Be7', 'O-O'],
    rating: 800,
    themes: ['development', 'opening'],
    title: 'Complete Development',
    description: 'Finish development first.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p23',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R w KQkq - 0 4',
    moves: ['dxe5', 'Nxe4', 'Qd5'],
    rating: 900,
    themes: ['tactic', 'discovered'],
    title: 'Discovered Attack',
    description: 'Open lines for an attack.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p24',
    fen: 'r1bqkb1r/ppp2ppp/2np1n2/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 5',
    moves: ['d3', 'Be7', 'O-O'],
    rating: 850,
    themes: ['strategy', 'development'],
    title: 'Solid Setup',
    description: 'Set up solidly.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p25',
    fen: 'r4rk1/ppp2ppp/2n5/3N4/3q4/8/PPP2PPP/R2Q1RK1 w - - 0 12',
    moves: ['Nxc7', 'Qxd1', 'Rfxd1'],
    rating: 950,
    themes: ['tactic', 'combination'],
    title: 'Win Material',
    description: 'Find the winning sequence.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p26',
    fen: '6k1/8/5KQ1/8/8/8/8/8 w - - 0 1',
    moves: ['Qg7#'],
    rating: 700,
    themes: ['mate', 'pattern'],
    title: 'Queen Mate Pattern',
    description: 'Find the simple checkmate.',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p27',
    fen: '7k/8/6B1/5B2/8/8/8/7K w - - 0 1',
    moves: ['Be4'],
    rating: 850,
    themes: ['endgame', 'bishops'],
    title: 'Bishop Restriction',
    description: 'Restrict the kings movement.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p28',
    fen: '8/8/4k3/8/8/8/8/4RK2 w - - 0 1',
    moves: ['Re4'],
    rating: 900,
    themes: ['endgame', 'rook'],
    title: 'Rook Cutoff',
    description: 'Cut off the king.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p29',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2B1n3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    moves: ['Bxf7+', 'Ke7', 'd3'],
    rating: 950,
    themes: ['tactic', 'sacrifice'],
    title: 'Win Material',
    description: 'Win material with a sacrifice.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p30',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 6 5',
    moves: ['d3', 'd6', 'c3'],
    rating: 900,
    themes: ['opening', 'italian'],
    title: 'Italian Classical',
    description: 'Build a solid position.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p31',
    fen: 'rnbqkb1r/pp2pppp/2p2n2/3p4/2PP4/2N5/PP2PPPP/R1BQKBNR w KQkq - 0 4',
    moves: ['e3', 'e6', 'Bd3'],
    rating: 950,
    themes: ['opening', 'slav'],
    title: 'Slav Defense',
    description: 'Play the Slav Defense setup.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p32',
    fen: 'r1bqkb1r/pp1npppp/2p2n2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 2 5',
    moves: ['e3', 'e6', 'Bd3'],
    rating: 900,
    themes: ['opening', 'qgd'],
    title: 'QGD Setup',
    description: 'Set up the Queens Gambit Declined.',
    difficulty: 'medium',
    xpReward: 25,
  },
  // === HARD PUZZLES (Rating 1100-1400) ===
  {
    id: 'p33',
    fen: 'r1b1k2r/ppppqppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 4 5',
    moves: ['Ng5', 'O-O', 'Nxh7'],
    rating: 1150,
    themes: ['attack', 'sacrifice'],
    title: 'Knight Attack',
    description: 'Launch a kingside attack.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p34',
    fen: 'r1bq1rk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQ1RK1 w - - 0 7',
    moves: ['h3', 'h6', 'Be3'],
    rating: 1200,
    themes: ['strategy', 'prophylaxis'],
    title: 'Prophylaxis',
    description: 'Prevent threats while improving.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p35',
    fen: 'r1b2rk1/ppp2ppp/2n2n2/3qp3/3P4/2N2N2/PPP2PPP/R1BQ1RK1 w - - 0 9',
    moves: ['dxe5', 'Nxe5', 'Nxe5'],
    rating: 1250,
    themes: ['tactic', 'exchange'],
    title: 'Exchange and Win',
    description: 'Win material precisely.',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p36',
    fen: 'r1bq1rk1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQR1K1 w - - 0 8',
    moves: ['Nd5', 'Nxd5', 'exd5'],
    rating: 1300,
    themes: ['strategy', 'outpost'],
    title: 'Knight Jump',
    description: 'Control key squares.',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p37',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3p4/1bPP4/2N1PN2/PP3PPP/R1BQKB1R w KQ - 0 6',
    moves: ['a3', 'Bxc3+', 'bxc3'],
    rating: 1200,
    themes: ['strategy', 'bishopPair'],
    title: 'Bishop Pair',
    description: 'Win the bishop pair.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p38',
    fen: 'r1bq1rk1/pp1n1ppp/2pbpn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 8',
    moves: ['b4', 'a6', 'a4'],
    rating: 1350,
    themes: ['strategy', 'minorityAttack'],
    title: 'Minority Attack',
    description: 'Attack the queenside.',
    difficulty: 'hard',
    xpReward: 45,
  },
  {
    id: 'p39',
    fen: 'r1bq1rk1/pppn1ppp/4pn2/3p4/1bPP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 2 7',
    moves: ['cxd5', 'exd5', 'Qc2'],
    rating: 1300,
    themes: ['strategy', 'openLines'],
    title: 'Open Lines',
    description: 'Open lines for pieces.',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p40',
    fen: 'rnbqkb1r/pppppp1p/5np1/8/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3',
    moves: ['Nc3', 'Bg7', 'e4'],
    rating: 1200,
    themes: ['opening', 'kingsIndian'],
    title: 'Kings Indian',
    description: 'Face the Kings Indian Defense.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p41',
    fen: 'r2q1rk1/pp2ppbp/2np1np1/8/3NP3/2N1B3/PPPQBPPP/R3K2R w KQ - 0 9',
    moves: ['O-O-O', 'Qa5', 'f3'],
    rating: 1400,
    themes: ['attack', 'sicilian'],
    title: 'Sicilian Dragon',
    description: 'Set up your attack.',
    difficulty: 'hard',
    xpReward: 45,
  },
  // === EXPERT PUZZLES (Rating 1500-1800) ===
  {
    id: 'p42',
    fen: '2r3k1/5ppp/8/8/8/8/5PPP/2R3K1 w - - 0 1',
    moves: ['Rc4', 'Kf8', 'Ra4'],
    rating: 1500,
    themes: ['endgame', 'simplification'],
    title: 'Rook Endgame',
    description: 'Improve your rook position.',
    difficulty: 'expert',
    xpReward: 50,
  },
  {
    id: 'p43',
    fen: '8/8/8/8/8/5k2/5P2/5K2 w - - 0 1',
    moves: ['Ke1', 'Ke4', 'Ke2'],
    rating: 1550,
    themes: ['endgame', 'pawnEndgame'],
    title: 'Pawn Endgame',
    description: 'Navigate correctly.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p44',
    fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/3NP3/2N1B3/PPPQBPPP/R3K2R w KQ - 0 9',
    moves: ['O-O-O', 'a6', 'f3'],
    rating: 1600,
    themes: ['attack', 'oppositeCastling'],
    title: 'Opposite Castling',
    description: 'Castle queenside and attack.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p45',
    fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/2BNP3/2N1B3/PPP2PPP/R2QK2R w KQ - 0 8',
    moves: ['Qd2', 'a6', 'O-O-O'],
    rating: 1650,
    themes: ['opening', 'sicilian'],
    title: 'Dragon Setup',
    description: 'Set up the Yugoslav Attack.',
    difficulty: 'expert',
    xpReward: 60,
  },
  {
    id: 'p46',
    fen: '8/5pk1/8/8/8/8/5PP1/6K1 w - - 0 1',
    moves: ['f4', 'Kf6', 'Kf2'],
    rating: 1500,
    themes: ['endgame', 'kingActivity'],
    title: 'King Activity',
    description: 'Activate your king.',
    difficulty: 'expert',
    xpReward: 50,
  },
  {
    id: 'p47',
    fen: 'r1bq1rk1/pp1nppbp/2np2p1/8/2BNP3/2N1BP2/PPPQ2PP/R3K2R w KQ - 0 9',
    moves: ['O-O-O', 'a6', 'g4'],
    rating: 1700,
    themes: ['attack', 'pawnStorm'],
    title: 'Kingside Storm',
    description: 'Launch a pawn storm.',
    difficulty: 'expert',
    xpReward: 65,
  },
  {
    id: 'p48',
    fen: 'r1b2rk1/pp2ppbp/2np1np1/q7/2BNP3/2N1BP2/PPPQ2PP/R3K2R w KQ - 0 10',
    moves: ['O-O-O', 'Qc7', 'h4'],
    rating: 1750,
    themes: ['attack', 'sicilian'],
    title: 'Yugoslav Attack',
    description: 'Continue with precision.',
    difficulty: 'expert',
    xpReward: 70,
  },
  {
    id: 'p49',
    fen: 'r2qk2r/pp1nbppp/2p1pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQK2R w KQkq - 2 8',
    moves: ['Qc2', 'O-O', 'O-O'],
    rating: 1600,
    themes: ['opening', 'qgd'],
    title: 'QGD Classical',
    description: 'Navigate the Queens Gambit.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p50',
    fen: 'rnbqkb1r/pp2pppp/5n2/2pp4/2PP4/2N5/PP2PPPP/R1BQKBNR w KQkq d6 0 4',
    moves: ['cxd5', 'Nxd5', 'e4'],
    rating: 1650,
    themes: ['opening', 'panov'],
    title: 'Panov Attack',
    description: 'Play the aggressive Panov.',
    difficulty: 'expert',
    xpReward: 60,
  },
  {
    id: 'p51',
    fen: 'rnbqkb1r/pp2pppp/5n2/3p4/3P4/2N2N2/PPP1PPPP/R1BQKB1R w KQkq - 2 4',
    moves: ['Bg5', 'e6', 'e3'],
    rating: 1500,
    themes: ['opening', 'london'],
    title: 'London System',
    description: 'Set up the solid London.',
    difficulty: 'expert',
    xpReward: 50,
  },
  {
    id: 'p52',
    fen: 'rnbqkb1r/ppp1pppp/5n2/3p4/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3',
    moves: ['cxd5', 'Nxd5', 'e4'],
    rating: 1550,
    themes: ['opening', 'queensGambit'],
    title: 'Queens Gambit',
    description: 'Fight for the center.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p53',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    moves: ['Bb5', 'a6', 'Ba4'],
    rating: 1700,
    themes: ['opening', 'ruyLopez'],
    title: 'Ruy Lopez',
    description: 'Play the classical Ruy Lopez.',
    difficulty: 'expert',
    xpReward: 65,
  },
  // === NEW PUZZLES (p54-p65) ===
  {
    id: 'p54',
    fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    moves: ['Re8#'],
    rating: 400,
    themes: ['mate', 'backRank'],
    title: 'Back Rank Mate',
    description: 'The king is stuck behind its own pawns. Deliver the final blow!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p55',
    fen: 'r1bqkb1r/pppppppp/2n2n2/8/3NP3/8/PPP2PPP/RNBQKB1R w KQkq - 2 4',
    moves: ['Nxc6', 'bxc6'],
    rating: 450,
    themes: ['tactics', 'capture'],
    title: 'Simple Fork',
    description: 'Capture the knight and damage Black\'s pawn structure.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p56',
    fen: 'rnb1kbnr/pppppppp/8/8/4q3/2N5/PPPPPPPP/R1BQKBNR w KQkq - 0 1',
    moves: ['Nxe4'],
    rating: 500,
    themes: ['tactics', 'capture'],
    title: 'Queen Capture',
    description: 'Black\'s queen has wandered into danger. Win the queen!',
    difficulty: 'easy',
    xpReward: 15,
  },
  {
    id: 'p57',
    fen: '8/4P1k1/8/8/8/8/6K1/8 w - - 0 1',
    moves: ['e8=Q'],
    rating: 550,
    themes: ['endgame', 'promotion'],
    title: 'Pawn Promotion',
    description: 'Push the pawn to promotion and get a new queen!',
    difficulty: 'easy',
    xpReward: 15,
  },
  {
    id: 'p58',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4',
    moves: ['Nxe4', 'Bxf7+', 'Kf8'],
    rating: 750,
    themes: ['tactics', 'sacrifice', 'fork'],
    title: 'Knight Fork Royal',
    description: 'Win a pawn but watch out for the bishop counter-strike!',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p59',
    fen: 'r2qkbnr/ppp2ppp/2np4/4p3/2B1P1b1/5N2/PPPP1PPP/RNBQ1RK1 w kq - 2 5',
    moves: ['Bxf7+', 'Kd7'],
    rating: 800,
    themes: ['tactics', 'sacrifice', 'discoveredAttack'],
    title: 'Discovered Attack',
    description: 'Sacrifice the bishop to expose the enemy king!',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p60',
    fen: 'rnbqk2r/pppp1ppp/4pn2/8/1bPP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 2 4',
    moves: ['Qb3', 'Bxc3+', 'bxc3'],
    rating: 900,
    themes: ['tactics', 'pin', 'strategy'],
    title: 'Pin and Win',
    description: 'Use the queen to exploit the pin on the knight!',
    difficulty: 'medium',
    xpReward: 30,
  },
  {
    id: 'p61',
    fen: 'r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1',
    moves: ['Nc7+', 'Kd8', 'Nxa8'],
    rating: 950,
    themes: ['tactics', 'fork', 'endgame'],
    title: 'Knight Fork',
    description: 'Fork the king and rook with the knight!',
    difficulty: 'medium',
    xpReward: 30,
  },
  {
    id: 'p62',
    fen: 'r1bq1rk1/pppn1ppp/4pn2/3p4/1bPP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 8',
    moves: ['cxd5', 'exd5', 'Nxd5'],
    rating: 1200,
    themes: ['tactics', 'sacrifice', 'centerControl'],
    title: 'Greek Gift Sacrifice',
    description: 'Break open the center and win a pawn with a tactical sequence!',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p63',
    fen: 'r1b2rk1/pp3ppp/2n1pn2/q2p4/3P4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 9',
    moves: ['Nb5', 'Qd8', 'Nc7'],
    rating: 1350,
    themes: ['tactics', 'fork', 'knightOutpost'],
    title: 'Knight Outpost',
    description: 'Drive the queen away and plant the knight deep in enemy territory!',
    difficulty: 'hard',
    xpReward: 45,
  },
  {
    id: 'p64',
    fen: 'r2q1rk1/ppp1bppp/2n1pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 8',
    moves: ['cxd5', 'exd5', 'Nxd5', 'Nxd5', 'Bxh7+'],
    rating: 1550,
    themes: ['sacrifice', 'tactics', 'attack'],
    title: 'Positional Sacrifice',
    description: 'Exchange pieces to open lines and launch a devastating bishop sacrifice!',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p65',
    fen: 'r1bq1rk1/pp2bppp/2n1pn2/2pp4/2PP4/2N1PN2/PPB2PPP/R1BQ1RK1 w - - 0 8',
    moves: ['cxd5', 'exd5', 'dxc5', 'Bxc5', 'b4'],
    rating: 1700,
    themes: ['strategy', 'pawnStructure', 'opening'],
    title: 'Exchange Sacrifice',
    description: 'Open lines and gain a positional advantage with precise pawn play!',
    difficulty: 'expert',
    xpReward: 65,
  },
  // === GENERATED PUZZLES (p66-p173) ===
  {
    id: "p66",
    fen: "6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1",
    moves: ["Ra8#"],
    rating: 400,
    themes: ["mate", "backRank"],
    title: "Back Rank Mate",
    description: "Deliver checkmate on the back rank with the rook!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p67",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    moves: ["Re8#"],
    rating: 400,
    themes: ["mate", "backRank"],
    title: "Rook Back Rank",
    description: "The enemy king is trapped behind its own pawns!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p68",
    fen: "6k1/5ppp/8/8/8/8/5PPP/1R4K1 w - - 0 1",
    moves: ["Rb8#"],
    rating: 420,
    themes: ["mate", "backRank"],
    title: "Back Rank Rook Mate",
    description: "Deliver checkmate on the back rank with the rook!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p69",
    fen: "4k3/8/8/8/8/8/8/4QK2 w - - 0 1",
    moves: ["Qe7#"],
    rating: 400,
    themes: ["mate"],
    title: "Queen Checkmate",
    description: "Deliver checkmate with the queen!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p70",
    fen: "k7/8/1K6/8/8/8/8/7Q w - - 0 1",
    moves: ["Qa8#"],
    rating: 400,
    themes: ["mate"],
    title: "Queen Delivers Mate",
    description: "Close in on the enemy king with checkmate!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p71",
    fen: "7k/8/6K1/8/8/8/8/Q7 w - - 0 1",
    moves: ["Qa8#"],
    rating: 400,
    themes: ["mate"],
    title: "Corner Queen Mate",
    description: "Checkmate the king in the corner!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p72",
    fen: "k7/8/1K6/8/8/8/8/R7 w - - 0 1",
    moves: ["Ra8#"],
    rating: 410,
    themes: ["mate"],
    title: "Rook Checkmate",
    description: "Use the rook to deliver checkmate!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p73",
    fen: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
    moves: ["d5"],
    rating: 400,
    themes: ["tactics", "opening"],
    title: "Center Counter",
    description: "Challenge the center pawn immediately!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p74",
    fen: "r1bqkbnr/pppppppp/2n5/4P3/8/8/PPPP1PPP/RNBQKBNR b KQkq - 0 2",
    moves: ["d6"],
    rating: 420,
    themes: ["tactics", "pawnBreak"],
    title: "Pawn Break",
    description: "Attack the advanced pawn to regain space!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p75",
    fen: "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/4P3/8/PPPP1PPP/RNB1KBNR w KQkq - 2 3",
    moves: ["Qxe5+"],
    rating: 430,
    themes: ["tactics", "fork"],
    title: "Queen Fork Check",
    description: "Win a pawn while giving check!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p76",
    fen: "r2qkbnr/ppp2ppp/2np4/4p3/2B1P1b1/5N2/PPPP1PPP/RNBQK2R w KQkq - 2 4",
    moves: ["Bxf7+"],
    rating: 450,
    themes: ["tactics", "sacrifice"],
    title: "Bishop Takes f7",
    description: "Capture the vulnerable f7 pawn with check!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p77",
    fen: "rnb1kbnr/pppp1ppp/8/4p3/4PP1q/8/PPPP2PP/RNBQKBNR w KQkq - 1 3",
    moves: ["g3"],
    rating: 460,
    themes: ["tactics", "trapped"],
    title: "Trap the Queen",
    description: "The queen is in danger after venturing out too early!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p78",
    fen: "r1bqkb1r/pppppppp/2n2n2/8/3NP3/8/PPP2PPP/RNBQKB1R w KQkq - 2 3",
    moves: ["Nxc6"],
    rating: 440,
    themes: ["tactics", "capture"],
    title: "Knight Captures",
    description: "Capture the knight on c6!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p79",
    fen: "4k3/8/8/8/3n4/8/8/4K2R w K - 0 1",
    moves: ["Rh8+"],
    rating: 400,
    themes: ["mate", "backRank"],
    title: "Back Rank With Rook",
    description: "Deliver a check on the back rank!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p80",
    fen: "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    moves: ["d3"],
    rating: 420,
    themes: ["opening", "development"],
    title: "Protect the Bishop",
    description: "Develop and protect the bishop on c4!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p81",
    fen: "5rk1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1",
    moves: ["Rd8"],
    rating: 450,
    themes: ["tactics", "backRank"],
    title: "Back Rank Threat",
    description: "Attack the back rank and force a trade!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p82",
    fen: "1k6/1pp5/1P6/8/8/8/5PPP/R5K1 w - - 0 1",
    moves: ["Ra8#"],
    rating: 400,
    themes: ["mate", "backRank"],
    title: "Trapped King Mate",
    description: "The king is locked behind its own pawns!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p83",
    fen: "5k2/8/5K2/8/8/8/8/4R3 w - - 0 1",
    moves: ["Re8#"],
    rating: 410,
    themes: ["mate", "endgame"],
    title: "Endgame Rook Mate",
    description: "Use the rook to deliver a checkmate!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p84",
    fen: "3k4/8/3K4/8/8/8/8/R7 w - - 0 1",
    moves: ["Ra8#"],
    rating: 400,
    themes: ["mate", "endgame"],
    title: "Rook Endgame Mate",
    description: "Finish the game with a rook checkmate!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p85",
    fen: "7k/5ppR/6p1/8/8/8/8/6K1 w - - 0 1",
    moves: ["Rh8#"],
    rating: 430,
    themes: ["mate", "backRank"],
    title: "Rook Slides to h8",
    description: "Deliver mate along the back rank!",
    difficulty: "easy",
    xpReward: 15,
  },
  {
    id: "p86",
    fen: "r4rk1/ppp2ppp/8/8/8/8/PPP2PPP/R4RK1 w - - 0 1",
    moves: ["Rab1"],
    rating: 400,
    themes: ["strategy", "development"],
    title: "Activate the Rook",
    description: "Place the rook on an open file!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p87",
    fen: "2k5/8/2K5/8/8/8/8/1R6 w - - 0 1",
    moves: ["Rb8#"],
    rating: 400,
    themes: ["mate", "endgame"],
    title: "Simple Rook Mate",
    description: "Checkmate with the rook!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p88",
    fen: "k7/2K5/8/8/8/8/8/1R6 w - - 0 1",
    moves: ["Rb8#"],
    rating: 400,
    themes: ["mate", "endgame"],
    title: "King & Rook Mate",
    description: "The king supports the rook for checkmate!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p89",
    fen: "1k6/8/1K6/8/8/8/8/7R w - - 0 1",
    moves: ["Rh8#"],
    rating: 400,
    themes: ["mate", "endgame"],
    title: "Edge Rook Mate",
    description: "The rook delivers mate from afar!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p90",
    fen: "6k1/5pp1/5n1p/8/4N3/8/5PPP/6K1 w - - 0 1",
    moves: ["Nf6+"],
    rating: 500,
    themes: ["tactics", "fork"],
    title: "Knight Fork Check",
    description: "Fork the king with a knight check!",
    difficulty: "easy",
    xpReward: 15,
  },
  {
    id: "p91",
    fen: "r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1",
    moves: ["O-O"],
    rating: 400,
    themes: ["opening", "castling"],
    title: "Castle Kingside",
    description: "Castle to safety!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p92",
    fen: "3qk3/8/8/8/8/8/6PP/6K1 b - - 0 1",
    moves: ["Qd1#"],
    rating: 420,
    themes: ["mate", "backRank"],
    title: "Queen Back Rank Mate",
    description: "Use the queen to deliver back rank mate!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p93",
    fen: "6k1/pp3ppp/8/2b5/8/8/PP3PPP/R3R1K1 w - - 0 1",
    moves: ["Re8+"],
    rating: 500,
    themes: ["tactics", "backRank"],
    title: "Back Rank Pressure",
    description: "Check the king on the back rank!",
    difficulty: "easy",
    xpReward: 15,
  },
  {
    id: "p94",
    fen: "r3r1k1/pp3ppp/8/2B5/8/8/PP3PPP/4R1K1 w - - 0 1",
    moves: ["Re8+"],
    rating: 500,
    themes: ["tactics", "backRank"],
    title: "Exchange on Back Rank",
    description: "Force an exchange with a back rank check!",
    difficulty: "easy",
    xpReward: 15,
  },
  {
    id: "p95",
    fen: "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4",
    moves: ["Nxe4"],
    rating: 600,
    themes: ["tactics", "capture"],
    title: "Win the Center Pawn",
    description: "Capture the center pawn while it is undefended!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p96",
    fen: "r2qk2r/ppp2ppp/2n1bn2/2bpp3/4P3/1BN2N2/PPPP1PPP/R1BQ1RK1 w kq - 0 6",
    moves: ["exd5"],
    rating: 620,
    themes: ["tactics", "capture"],
    title: "Central Tension",
    description: "Resolve the tension in the center favorably!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p97",
    fen: "r1bqr1k1/ppp2ppp/2n2n2/3p4/1b1P4/2N1PN2/PP3PPP/R1BQKB1R w KQ - 0 7",
    moves: ["Bd3"],
    rating: 650,
    themes: ["development", "opening"],
    title: "Bishop Development",
    description: "Develop the bishop to a good square!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p98",
    fen: "2kr3r/ppp1qppp/2n2n2/3p4/3P4/2N2N2/PPP2PPP/R2QR1K1 w - - 0 10",
    moves: ["Nxd5"],
    rating: 700,
    themes: ["tactics", "capture"],
    title: "Central Knight Capture",
    description: "Win the center pawn with the knight!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p99",
    fen: "r1b1kb1r/pppp1ppp/2n2n2/1B2p1q1/4P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 4",
    moves: ["Nxe5"],
    rating: 750,
    themes: ["tactics", "capture", "fork"],
    title: "Win the e5 Pawn",
    description: "Capture the pawn and attack the queen!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p100",
    fen: "r1bq1rk1/pppp1ppp/2n2n2/2b1N3/2B1P3/8/PPPP1PPP/RNBQ1RK1 b - - 0 5",
    moves: ["Bxf2+"],
    rating: 800,
    themes: ["sacrifice", "tactics"],
    title: "Bishop Sacrifice",
    description: "Sacrifice the bishop to disrupt the king!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p101",
    fen: "6rk/6pp/8/6N1/8/8/8/7K w - - 0 1",
    moves: ["Nf7#"],
    rating: 650,
    themes: ["mate", "smotheredMate"],
    title: "Smothered Mate",
    description: "The knight delivers a beautiful smothered checkmate!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p102",
    fen: "r4rk1/5ppp/8/1n6/8/5N2/5PPP/R4RK1 w - - 0 1",
    moves: ["Ng5"],
    rating: 600,
    themes: ["tactics", "attack"],
    title: "Knight Attack",
    description: "Reposition the knight to threaten the kingside!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p103",
    fen: "r2q1rk1/pp2ppbp/2np1np1/8/2PNP3/2N1BP2/PP4PP/R2Q1RK1 b - - 0 10",
    moves: ["d5"],
    rating: 700,
    themes: ["strategy", "pawnBreak"],
    title: "Central Break",
    description: "Strike in the center to open lines!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p104",
    fen: "2r2rk1/pp2ppbp/3p1np1/q7/2PNP3/2N1BP2/PP2Q1PP/R4RK1 w - - 0 12",
    moves: ["Nd5"],
    rating: 750,
    themes: ["tactics", "knightOutpost"],
    title: "Knight to d5",
    description: "Place the knight on the powerful d5 outpost!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p105",
    fen: "r3kb1r/pp1n1ppp/2p2n2/q2pp1B1/2PP4/2N2N2/PP2PPPP/R2QKB1R w KQkq - 0 6",
    moves: ["cxd5"],
    rating: 650,
    themes: ["tactics", "capture"],
    title: "Pawn Exchange",
    description: "Open the center with a pawn exchange!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p106",
    fen: "rnbq1rk1/ppp1ppbp/3p1np1/8/2PPP3/2N2N2/PP2BPPP/R1BQK2R w KQ - 0 6",
    moves: ["O-O"],
    rating: 600,
    themes: ["opening", "castling", "strategy"],
    title: "Classical Setup",
    description: "Complete development with castling!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p107",
    fen: "r3k2r/ppp2ppp/2n5/3np3/2B5/5Q2/PPP2PPP/R3K2R w KQkq - 0 10",
    moves: ["Qf7+"],
    rating: 800,
    themes: ["tactics", "fork", "doubleAttack"],
    title: "Queen Fork",
    description: "Attack the king and the knight at the same time!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p108",
    fen: "r1b1k2r/pppp1ppp/2n2n2/2b1N3/4P3/8/PPPP1PPP/RNBQKB1R w KQkq - 0 4",
    moves: ["Nxc6"],
    rating: 600,
    themes: ["tactics", "capture"],
    title: "Knight Wins Piece",
    description: "Capture the undefended knight!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p109",
    fen: "4k3/8/8/2b5/8/3N4/3K4/8 w - - 0 1",
    moves: ["Nxc5"],
    rating: 600,
    themes: ["tactics", "capture", "endgame"],
    title: "Knight Takes Bishop",
    description: "Win material by capturing the bishop!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p110",
    fen: "6k1/5p1p/6p1/8/3B4/8/5PPP/6K1 w - - 0 1",
    moves: ["Bc5"],
    rating: 650,
    themes: ["strategy", "endgame"],
    title: "Active Bishop",
    description: "Centralize the bishop for maximum activity!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p111",
    fen: "r1bqkb1r/pppp1Npp/2n2n2/4p3/4P3/8/PPPP1PPP/RNBQKB1R b KQkq - 0 4",
    moves: ["Qe7"],
    rating: 750,
    themes: ["tactics", "defense"],
    title: "Defend Against Knight",
    description: "Find the best defensive move against the knight invasion!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p112",
    fen: "r1bqkb1r/pppp1ppp/2n5/4p3/2B1n3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 0 5",
    moves: ["d3"],
    rating: 650,
    themes: ["tactics", "pin"],
    title: "Attack the Pinned Knight",
    description: "The knight on e4 has nowhere safe to go!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p113",
    fen: "r1bqkb1r/pppppppp/2n2n2/8/2BPP3/8/PPP2PPP/RNBQK1NR b KQkq - 0 3",
    moves: ["Nxe4"],
    rating: 700,
    themes: ["tactics", "capture"],
    title: "Win the e-Pawn",
    description: "The e4 pawn is underdefended, take it!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p114",
    fen: "r1bqkb1r/pppp1ppp/2n2n2/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3",
    moves: ["Nxe4"],
    rating: 750,
    themes: ["tactics", "capture"],
    title: "Ruy Lopez Trap",
    description: "Win a pawn in the Ruy Lopez opening!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p115",
    fen: "rnbqk2r/pppp1ppp/5n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    moves: ["Ng5"],
    rating: 700,
    themes: ["tactics", "attack"],
    title: "Fried Liver Attack",
    description: "Attack f7 with the knight!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p116",
    fen: "r1b1kb1r/pppp1ppp/2n2n2/4p2q/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    moves: ["Nc3"],
    rating: 600,
    themes: ["development", "opening"],
    title: "Develop with Tempo",
    description: "Develop the knight while preparing to defend!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p117",
    fen: "r1bq1rk1/ppppbppp/2n2n2/4p3/2B1P3/3P1N2/PPP2PPP/RNBQ1RK1 w - - 0 6",
    moves: ["Re1"],
    rating: 620,
    themes: ["strategy", "development"],
    title: "Rook to Open File",
    description: "Place the rook behind the e-pawn!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p118",
    fen: "3r2k1/pp3ppp/8/8/4n3/4B3/PP3PPP/3R2K1 w - - 0 1",
    moves: ["Rd8+"],
    rating: 800,
    themes: ["tactics", "backRank"],
    title: "Rook Back Rank Intermezzo",
    description: "Play a forcing back rank check first!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p119",
    fen: "4k3/pppp1ppp/8/8/8/8/PPPPQPPP/4K3 w - - 0 1",
    moves: ["Qe7#"],
    rating: 600,
    themes: ["mate"],
    title: "Queen Checkmate Pattern",
    description: "Deliver checkmate with the queen!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p120",
    fen: "r3k2r/pppqbppp/2n1pn2/3p4/3P4/2NBPN2/PPP2PPP/R2QK2R w KQkq - 0 7",
    moves: ["O-O"],
    rating: 600,
    themes: ["opening", "castling"],
    title: "Castle Into Safety",
    description: "Get the king to safety before the middlegame!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p121",
    fen: "rnbq1rk1/pppp1ppp/4pn2/8/1bPP4/2N2N2/PP2PPPP/R1BQKB1R w KQ - 0 4",
    moves: ["e3"],
    rating: 620,
    themes: ["opening", "development"],
    title: "Nimzo-Indian Defense",
    description: "Solidify the center and prepare to develop!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p122",
    fen: "r2qr1k1/ppp2ppp/2n5/3N4/2BP4/8/PPP2PPP/R2Q1RK1 w - - 0 12",
    moves: ["Nf6+"],
    rating: 900,
    themes: ["tactics", "fork", "discoveredAttack"],
    title: "Knight Fork Discovery",
    description: "The knight delivers a devastating fork!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p123",
    fen: "2r3k1/pp3pp1/2n4p/3N4/8/6P1/PP3P1P/3R2K1 w - - 0 1",
    moves: ["Ne7+"],
    rating: 950,
    themes: ["tactics", "fork"],
    title: "Knight Forks King & Rook",
    description: "Fork the king and rook with the knight!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p124",
    fen: "r4rk1/ppp2Qpp/2n5/8/2B5/8/PPP2PPP/R5K1 w - - 0 12",
    moves: ["Qxf8#"],
    rating: 900,
    themes: ["mate", "capture"],
    title: "Queen Takes With Mate",
    description: "Capture the rook and deliver checkmate!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p125",
    fen: "r1bqk2r/pppp1ppp/2n2n2/4p3/1b2P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 4 4",
    moves: ["d3"],
    rating: 950,
    themes: ["tactics", "development"],
    title: "Develop With Purpose",
    description: "Support the center and prepare to chase the bishop!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p126",
    fen: "r1bq1rk1/pp2bppp/2n1p3/3pP3/3P1B2/2N2N2/PPP2PPP/R2QR1K1 w - - 0 9",
    moves: ["Ng5"],
    rating: 1000,
    themes: ["tactics", "attack"],
    title: "Kingside Attack",
    description: "Bring the knight into the attack!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p127",
    fen: "r1b1k2r/ppppnppp/2n5/1Bb1P3/8/5N2/PPPP1PPP/RNB1K2R w KQkq - 0 5",
    moves: ["Bxc6"],
    rating: 1000,
    themes: ["tactics", "capture"],
    title: "Win the Knight Pair",
    description: "Exchange the bishop for a knight and disrupt pawns!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p128",
    fen: "r2q1rk1/pp2ppbp/2np1np1/2p5/4P3/2NP1NP1/PPP2PBP/R1BQ1RK1 w - - 0 8",
    moves: ["e5"],
    rating: 1050,
    themes: ["strategy", "pawnBreak"],
    title: "Central Advance",
    description: "Push the e-pawn to seize space and attack!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p129",
    fen: "rn1qkb1r/ppp2ppp/4pn2/3p1b2/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 0 4",
    moves: ["cxd5"],
    rating: 900,
    themes: ["tactics", "capture", "opening"],
    title: "Exchange Variation",
    description: "Exchange pawns to open up the position!",
    difficulty: "hard",
    xpReward: 30,
  },
  {
    id: "p130",
    fen: "r2qk2r/ppp1ppbp/2n3p1/3n4/3P4/2N1BN2/PPP2PPP/R2QKB1R w KQkq - 0 7",
    moves: ["Nxd5"],
    rating: 1100,
    themes: ["tactics", "capture"],
    title: "Central Knight Win",
    description: "Capture the central knight and dominate!",
    difficulty: "hard",
    xpReward: 40,
  },
  {
    id: "p131",
    fen: "r4rk1/ppp2ppp/8/3Pb3/4p3/8/PPPB1PPP/2KR3R w - - 0 13",
    moves: ["d6"],
    rating: 1100,
    themes: ["tactics", "passed"],
    title: "Passed Pawn Push",
    description: "Push the passed pawn to create threats!",
    difficulty: "hard",
    xpReward: 40,
  },
  {
    id: "p132",
    fen: "r2q1rk1/pp3ppp/2p1bn2/3p4/3P4/2PB1N2/PP3PPP/R2Q1RK1 w - - 0 10",
    moves: ["Ne5"],
    rating: 1000,
    themes: ["strategy", "knightOutpost"],
    title: "Knight Outpost e5",
    description: "Plant the knight on the strong e5 outpost!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p133",
    fen: "2r1r1k1/pp3ppp/2n2b2/3p4/3N4/1P3PP1/PB3P1P/R3R1K1 w - - 0 18",
    moves: ["Nxc6"],
    rating: 1050,
    themes: ["tactics", "capture"],
    title: "Win the Exchange",
    description: "Capture the knight to gain material!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p134",
    fen: "r1b2rk1/pp3ppp/2n1p3/q1ppP3/3P4/P1P2N2/1P3PPP/R1BQKB1R w KQ - 0 9",
    moves: ["dxc5"],
    rating: 950,
    themes: ["tactics", "capture"],
    title: "Pawn Advance",
    description: "Win a pawn in the center!",
    difficulty: "hard",
    xpReward: 30,
  },
  {
    id: "p135",
    fen: "5rk1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    moves: ["Re8"],
    rating: 480,
    themes: ["tactics", "backRank"],
    title: "Rook Invades",
    description: "Infiltrate on the back rank!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p136",
    fen: "6k1/5ppp/8/8/8/5N2/5PPP/6K1 w - - 0 1",
    moves: ["Ne5"],
    rating: 450,
    themes: ["strategy", "development"],
    title: "Active Knight",
    description: "Centralize the knight on e5!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p137",
    fen: "r1bqkbnr/pppppppp/2n5/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 1 2",
    moves: ["d4"],
    rating: 400,
    themes: ["opening", "development"],
    title: "Claim the Center",
    description: "Establish a strong pawn center with d4!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p138",
    fen: "rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1",
    moves: ["d5"],
    rating: 400,
    themes: ["opening", "development"],
    title: "Mirror the Center",
    description: "Fight for the center immediately!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p139",
    fen: "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
    moves: ["Nf3"],
    rating: 400,
    themes: ["opening", "development"],
    title: "Develop the Knight",
    description: "Develop a piece and attack the e5 pawn!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p140",
    fen: "r1bqkbnr/pppppppp/2n5/8/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 2 2",
    moves: ["d6"],
    rating: 420,
    themes: ["opening", "development"],
    title: "Pirc Defense",
    description: "Defend the center and prepare fianchetto!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p141",
    fen: "4k3/8/8/8/8/5Q2/8/4K3 w - - 0 1",
    moves: ["Qf7#"],
    rating: 410,
    themes: ["mate", "endgame"],
    title: "Queen Endgame Mate",
    description: "Deliver checkmate with the queen!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p142",
    fen: "k7/1p6/1K6/8/8/8/8/R7 w - - 0 1",
    moves: ["Ra8#"],
    rating: 420,
    themes: ["mate", "endgame"],
    title: "Rook Mates With King",
    description: "The rook delivers mate with king support!",
    difficulty: "easy",
    xpReward: 10,
  },
  {
    id: "p143",
    fen: "6k1/5p1p/6pQ/8/8/8/8/6K1 w - - 0 1",
    moves: ["Qg7#"],
    rating: 430,
    themes: ["mate"],
    title: "Queen Mates on g7",
    description: "Deliver checkmate on the dark squares!",
    difficulty: "easy",
    xpReward: 15,
  },
  {
    id: "p144",
    fen: "r1bqk2r/pppp1ppp/2n2n2/2b1p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 4 4",
    moves: ["d4"],
    rating: 700,
    themes: ["tactics", "pawnBreak", "opening"],
    title: "Open the Center",
    description: "Strike in the center to challenge black!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p145",
    fen: "rnbqk2r/pppp1ppp/5n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4",
    moves: ["d6"],
    rating: 600,
    themes: ["opening", "development"],
    title: "Solid Defense",
    description: "Defend the center with a solid pawn move!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p146",
    fen: "r1bq1rk1/pppp1ppp/2n2n2/4p3/1bB1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w - - 6 5",
    moves: ["d3"],
    rating: 650,
    themes: ["strategy", "development"],
    title: "Solid Center",
    description: "Reinforce the center with d3!",
    difficulty: "medium",
    xpReward: 20,
  },
  {
    id: "p147",
    fen: "rnbq1rk1/ppp2ppp/3bpn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQ - 0 5",
    moves: ["Bg5"],
    rating: 750,
    themes: ["development", "pin"],
    title: "Pin the Knight",
    description: "Pin the knight to the queen with the bishop!",
    difficulty: "medium",
    xpReward: 25,
  },
  {
    id: "p148",
    fen: "4k3/8/8/8/8/8/4r3/R6K w - - 0 1",
    moves: ["Ra8+"],
    rating: 1000,
    themes: ["tactics", "skewer"],
    title: "Rook Skewer",
    description: "Skewer the king and win the rook!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p149",
    fen: "8/8/8/2k5/8/8/1K2B3/3r4 w - - 0 1",
    moves: ["Ba6+"],
    rating: 1100,
    themes: ["tactics", "skewer"],
    title: "Bishop Skewer",
    description: "Skewer the king and rook with the bishop!",
    difficulty: "hard",
    xpReward: 40,
  },
  {
    id: "p150",
    fen: "r1b1k2r/ppppqppp/2n5/2b1p3/2B1P1n1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 6 5",
    moves: ["O-O"],
    rating: 900,
    themes: ["tactics", "castling"],
    title: "Castle Under Pressure",
    description: "Castle to safety and connect the rooks!",
    difficulty: "hard",
    xpReward: 30,
  },
  {
    id: "p151",
    fen: "r1bq1rk1/ppp2ppp/2n1pn2/3p4/2PP4/2N2NP1/PP2PPBP/R1BQ1RK1 b - - 0 7",
    moves: ["dxc4"],
    rating: 900,
    themes: ["tactics", "capture"],
    title: "Win the c-Pawn",
    description: "Capture the c4 pawn to gain material!",
    difficulty: "hard",
    xpReward: 30,
  },
  {
    id: "p152",
    fen: "2rr2k1/pp3ppp/2n1p3/2Np4/3P4/4P3/PP3PPP/R2R2K1 w - - 0 16",
    moves: ["Nxe6"],
    rating: 1150,
    themes: ["tactics", "fork", "capture"],
    title: "Knight Snags Pawn",
    description: "Win a pawn with a tactical knight maneuver!",
    difficulty: "hard",
    xpReward: 40,
  },
  {
    id: "p153",
    fen: "r1bqk2r/pppp1ppp/2n2n2/4N3/2B1P3/8/PPPP1PPP/RNBQK2R b KQkq - 0 4",
    moves: ["d5"],
    rating: 900,
    themes: ["tactics", "counterplay"],
    title: "Counter in Center",
    description: "Strike back in the center with a pawn push!",
    difficulty: "hard",
    xpReward: 30,
  },
  {
    id: "p154",
    fen: "r2q1rk1/pppbbppp/2n1pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 8",
    moves: ["cxd5"],
    rating: 1200,
    themes: ["tactics", "capture", "opening"],
    title: "Exchange and Open",
    description: "Open the position for the bishops!",
    difficulty: "hard",
    xpReward: 40,
  },
  {
    id: "p155",
    fen: "3r2k1/ppp2ppp/8/3Pp3/8/1B6/PPP2PPP/3R2K1 w - - 0 1",
    moves: ["d6"],
    rating: 1100,
    themes: ["strategy", "passed", "endgame"],
    title: "Push the Passed Pawn",
    description: "Advance the passed pawn toward promotion!",
    difficulty: "hard",
    xpReward: 40,
  },
  {
    id: "p156",
    fen: "r2qk2r/pp1n1ppp/2pb1n2/4p3/2BPP1b1/2N2N2/PPP2PPP/R1BQ1RK1 w kq - 0 7",
    moves: ["dxe5"],
    rating: 950,
    themes: ["tactics", "capture"],
    title: "Central Exchange",
    description: "Open the d-file with a pawn exchange!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p157",
    fen: "2r3k1/pp3ppp/4rn2/2pp4/8/1P2PN2/PB3PPP/R4RK1 w - - 0 17",
    moves: ["Bxf6"],
    rating: 1050,
    themes: ["tactics", "capture"],
    title: "Bishop Takes Knight",
    description: "Capture the knight and damage the pawn structure!",
    difficulty: "hard",
    xpReward: 35,
  },
  {
    id: "p158",
    fen: "r1b2rk1/ppq1ppbp/2np1np1/8/2PNP3/2N1BP2/PP4PP/R2Q1RK1 w - - 0 10",
    moves: ["Nc2"],
    rating: 900,
    themes: ["strategy", "development"],
    title: "Knight Repositioning",
    description: "Reroute the knight for better placement!",
    difficulty: "hard",
    xpReward: 30,
  },
  {
    id: "p159",
    fen: "r2qr1k1/ppp2ppp/2n5/2bNp3/8/3B4/PPP2PPP/R2QR1K1 w - - 0 12",
    moves: ["Nf6+"],
    rating: 1400,
    themes: ["tactics", "fork", "discoveredAttack"],
    title: "Knight Fork Discovery",
    description: "The knight delivers check and discovers an attack!",
    difficulty: "expert",
    xpReward: 50,
  },
  {
    id: "p160",
    fen: "r3k2r/ppq1bppp/2n1pn2/2pp4/2PP4/2NBPN2/PP3PPP/R2Q1RK1 w kq - 0 8",
    moves: ["cxd5", "exd5", "e4"],
    rating: 1500,
    themes: ["strategy", "pawnBreak"],
    title: "Central Pawn Storm",
    description: "Open the center with a pawn break sequence!",
    difficulty: "expert",
    xpReward: 55,
  },
  {
    id: "p161",
    fen: "r1bq1rk1/pp3ppp/2n1pn2/2ppN3/3P4/2N1P3/PPP2PPP/R1BQKB1R w KQ - 0 7",
    moves: ["Nxc6", "bxc6", "dxc5"],
    rating: 1450,
    themes: ["tactics", "capture"],
    title: "Piece Exchange Combo",
    description: "Exchange favorably then win a pawn!",
    difficulty: "expert",
    xpReward: 50,
  },
  {
    id: "p162",
    fen: "r2q1rk1/pp1bbppp/2n1pn2/2pp4/2PP4/1PN1PN2/PB3PPP/R2QKB1R w KQ - 0 8",
    moves: ["cxd5", "exd5", "dxc5"],
    rating: 1550,
    themes: ["strategy", "pawnStructure"],
    title: "IQP Strategy",
    description: "Create an isolated queen pawn for your opponent!",
    difficulty: "expert",
    xpReward: 55,
  },
  {
    id: "p163",
    fen: "r1bq1rk1/pp2ppbp/2n2np1/2pp4/2PP4/2N1PN2/PP2BPPP/R1BQ1RK1 w - - 0 7",
    moves: ["dxc5", "dxc4", "Bxc4"],
    rating: 1500,
    themes: ["strategy", "opening"],
    title: "Catalan Opening",
    description: "Win a pawn with the Catalan bishop!",
    difficulty: "expert",
    xpReward: 55,
  },
  {
    id: "p164",
    fen: "r1bq1rk1/pppn1ppp/4pn2/3p4/1bPP4/2NBP3/PP3PPP/R1BQK1NR w KQ - 0 6",
    moves: ["cxd5", "exd5", "Nge2"],
    rating: 1400,
    themes: ["strategy", "opening"],
    title: "Nimzo Development",
    description: "Open the center and develop the knight!",
    difficulty: "expert",
    xpReward: 50,
  },
  {
    id: "p165",
    fen: "r2q1rk1/pp2bppp/2n1pn2/3p4/3P1B2/2N1PN2/PPP2PPP/R2QR1K1 w - - 0 9",
    moves: ["Ne5", "Nxe5", "Bxe5"],
    rating: 1450,
    themes: ["strategy", "piece_exchange"],
    title: "Knight for Knight",
    description: "Exchange knights and maintain the bishop!",
    difficulty: "expert",
    xpReward: 50,
  },
  {
    id: "p166",
    fen: "r3r1k1/pppq1ppp/2n2b2/3p4/3Pn3/2N1BN2/PPP2PPP/R2QR1K1 w - - 0 10",
    moves: ["Nxe4"],
    rating: 1400,
    themes: ["tactics", "capture"],
    title: "Central Knight Capture",
    description: "Win the powerful centralized knight!",
    difficulty: "expert",
    xpReward: 50,
  },
  {
    id: "p167",
    fen: "r2q1rk1/pp2ppbp/3p1np1/2pP4/4P3/2N5/PP2BPPP/R1BQ1RK1 w - - 0 10",
    moves: ["e5"],
    rating: 1500,
    themes: ["strategy", "pawnBreak", "attack"],
    title: "e5 Breakthrough",
    description: "Push e5 to open lines against the king!",
    difficulty: "expert",
    xpReward: 55,
  },
  {
    id: "p168",
    fen: "2rq1rk1/pp1bppbp/2np1np1/8/2PNP3/2N1BP2/PP4PP/R2Q1RK1 w - - 0 10",
    moves: ["Nd5"],
    rating: 1600,
    themes: ["strategy", "knightOutpost"],
    title: "Dragon Knight Outpost",
    description: "Place the knight on the dominant d5 square!",
    difficulty: "expert",
    xpReward: 55,
  },
  {
    id: "p169",
    fen: "r1bq1rk1/pp2bppp/2n1pn2/2ppN3/2PP4/2N1P3/PP3PPP/R1BQKB1R w KQ - 0 7",
    moves: ["Nxc6", "bxc6", "f3"],
    rating: 1700,
    themes: ["strategy", "pawnStructure"],
    title: "Positional Exchange",
    description: "Exchange and prepare a strong pawn center!",
    difficulty: "expert",
    xpReward: 60,
  },
  {
    id: "p170",
    fen: "r2q1rk1/pp1bbppp/2n1p3/3pPn2/3P1B2/2N2N2/PPP2PPP/R2QR1K1 w - - 0 10",
    moves: ["Bg5"],
    rating: 1450,
    themes: ["tactics", "pin"],
    title: "Pin the Bishop",
    description: "Pin the bishop to the queen with Bg5!",
    difficulty: "expert",
    xpReward: 50,
  },
  {
    id: "p171",
    fen: "r2qr1k1/pppb1ppp/2n2n2/3p4/3P4/1QN1PN2/PP3PPP/R1B2RK1 w - - 0 10",
    moves: ["Qb5"],
    rating: 1500,
    themes: ["tactics", "doubleAttack"],
    title: "Queen Pressure",
    description: "Attack the knight and pressure d5!",
    difficulty: "expert",
    xpReward: 55,
  },
  {
    id: "p172",
    fen: "r1bq1rk1/pp2ppbp/2np1np1/8/2PNP3/2N3P1/PP2PPBP/R1BQ1RK1 b - - 0 8",
    moves: ["d5"],
    rating: 1400,
    themes: ["strategy", "pawnBreak"],
    title: "Dragon Central Break",
    description: "Strike in the center with the thematic d5 break!",
    difficulty: "expert",
    xpReward: 50,
  },
  {
    id: "p173",
    fen: "r2q1rk1/pp3ppp/2p1bn2/3pN3/3P4/2N1P3/PPP2PPP/R2Q1RK1 w - - 0 11",
    moves: ["f3"],
    rating: 1450,
    themes: ["strategy", "prophylaxis"],
    title: "Prophylactic Move",
    description: "Prevent counterplay before continuing the attack!",
    difficulty: "expert",
    xpReward: 50,
  },
]

