import type { Puzzle } from '../chess-data'

export const PUZZLES: Puzzle[] = [
  // === EASY PUZZLES (Rating 400-600) ===
  {
    id: 'p1',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    moves: ['Qxf7#'],
    rating: 400,
    themes: ['mate', 'scholarsMate'],
    title: "Scholar's Mate",
    description: 'Find the checkmate in one move!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p2',
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2',
    moves: ['Qh4#'],
    rating: 400,
    themes: ['mate', 'foolsMate'],
    title: "Fool's Mate",
    description: 'White has weakened the kingside terribly!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p3',
    fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    moves: ['Re8#'],
    rating: 450,
    themes: ['mate', 'backRank'],
    title: 'Back Rank Mate',
    description: 'The king is trapped. Find checkmate!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p4',
    fen: '8/8/8/8/8/1k6/8/1K1Q4 w - - 0 1',
    moves: ['Qd3#'],
    rating: 450,
    themes: ['mate', 'queenMate'],
    title: 'Queen Checkmate',
    description: 'Deliver checkmate with queen support.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p5',
    fen: '8/8/8/8/8/1k6/R7/1K6 w - - 0 1',
    moves: ['Ra3#'],
    rating: 450,
    themes: ['mate', 'rookMate'],
    title: 'Rook Checkmate',
    description: 'Deliver checkmate with rook support.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p6',
    fen: '6k1/5ppp/8/8/8/8/5PPP/R3R1K1 w - - 0 1',
    moves: ['Re8#'],
    rating: 500,
    themes: ['mate', 'backRank'],
    title: 'Double Rook Power',
    description: 'Deliver the back rank mate!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p7',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    moves: ['Ng5'],
    rating: 550,
    themes: ['attack', 'threat'],
    title: 'Attack f7',
    description: 'Threaten the weak f7 pawn.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p8',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    moves: ['Bc4'],
    rating: 550,
    themes: ['development', 'opening'],
    title: 'Italian Opening',
    description: 'Find the best developing move.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p9',
    fen: '6rk/6pp/8/6N1/8/8/8/6K1 w - - 0 1',
    moves: ['Nf7#'],
    rating: 500,
    themes: ['mate', 'smotheredMate'],
    title: 'Smothered Mate',
    description: 'Deliver checkmate with the knight!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p10',
    fen: '5rk1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1',
    moves: ['Qd8'],
    rating: 550,
    themes: ['tactic', 'backRank'],
    title: 'Queen Threat',
    description: 'Force an exchange with back rank threat.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p11',
    fen: 'rnbqkbnr/ppp2ppp/8/3pp3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq d6 0 3',
    moves: ['Nxe5'],
    rating: 600,
    themes: ['tactic', 'capture'],
    title: 'Free Pawn',
    description: 'Capture the undefended pawn.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p12',
    fen: 'r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3',
    moves: ['a6'],
    rating: 600,
    themes: ['defense', 'kickBishop'],
    title: 'Kick the Bishop',
    description: 'Challenge Whites strong bishop.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p13',
    fen: '4k3/8/8/8/8/3R4/8/4K3 w - - 0 1',
    moves: ['Rd8+'],
    rating: 500,
    themes: ['tactic', 'check'],
    title: 'Rook Check',
    description: 'Give check to improve position.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p14',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    moves: ['Ng5', 'd5', 'exd5'],
    rating: 600,
    themes: ['attack', 'opening'],
    title: 'Fried Liver Setup',
    description: 'Begin the famous attack!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p15',
    fen: 'rnbqkb1r/pppppppp/5n2/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 1 2',
    moves: ['e5'],
    rating: 550,
    themes: ['opening', 'space'],
    title: 'Gain Space',
    description: 'Push the pawn to attack.',
    difficulty: 'easy',
    xpReward: 10,
  },
  // === MEDIUM PUZZLES (Rating 700-950) ===
  {
    id: 'p16',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 5',
    moves: ['Bg5', 'h6', 'Bh4'],
    rating: 750,
    themes: ['pin', 'pressure'],
    title: 'Pin the Knight',
    description: 'Use a pin to apply pressure.',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p17',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 5',
    moves: ['O-O', 'O-O', 'Nc3'],
    rating: 750,
    themes: ['development', 'castling'],
    title: 'Castle and Develop',
    description: 'Get king to safety.',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p18',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 4 4',
    moves: ['Nxe5', 'Nxe5', 'd4'],
    rating: 800,
    themes: ['tactic', 'fork'],
    title: 'Fork Trick',
    description: 'Win a pawn tactically.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p19',
    fen: 'rnbqkb1r/pppp1ppp/5n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    moves: ['d3', 'd6', 'Bg5'],
    rating: 800,
    themes: ['opening', 'development'],
    title: 'Italian Game',
    description: 'Build up pressure.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p20',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    moves: ['Qf7#'],
    rating: 700,
    themes: ['mate', 'tactics'],
    title: 'Quick Strike',
    description: 'Find the instant checkmate!',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p21',
    fen: 'rnbqkb1r/ppp2ppp/3p1n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    moves: ['d4', 'exd4', 'Nxd4'],
    rating: 850,
    themes: ['center', 'pawnBreak'],
    title: 'Central Break',
    description: 'Open up the center.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p22',
    fen: 'rnbqkb1r/ppp2ppp/3p1n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    moves: ['Nc3', 'Be7', 'O-O'],
    rating: 800,
    themes: ['development', 'opening'],
    title: 'Complete Development',
    description: 'Finish development first.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p23',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R w KQkq - 0 4',
    moves: ['dxe5', 'Nxe4', 'Qd5'],
    rating: 900,
    themes: ['tactic', 'discovered'],
    title: 'Discovered Attack',
    description: 'Open lines for an attack.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p24',
    fen: 'r1bqkb1r/ppp2ppp/2np1n2/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 5',
    moves: ['d3', 'Be7', 'O-O'],
    rating: 850,
    themes: ['strategy', 'development'],
    title: 'Solid Setup',
    description: 'Set up solidly.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p25',
    fen: 'r4rk1/ppp2ppp/2n5/3N4/3q4/8/PPP2PPP/R2Q1RK1 w - - 0 12',
    moves: ['Nxc7', 'Qxd1', 'Rfxd1'],
    rating: 950,
    themes: ['tactic', 'combination'],
    title: 'Win Material',
    description: 'Find the winning sequence.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p26',
    fen: '6k1/8/8/8/8/8/6Q1/6K1 w - - 0 1',
    moves: ['Qg7#'],
    rating: 700,
    themes: ['mate', 'pattern'],
    title: 'Queen Mate Pattern',
    description: 'Find the simple checkmate.',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p27',
    fen: '7k/8/6B1/5B2/8/8/8/7K w - - 0 1',
    moves: ['Be4'],
    rating: 850,
    themes: ['endgame', 'bishops'],
    title: 'Bishop Restriction',
    description: 'Restrict the kings movement.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p28',
    fen: '8/8/4k3/8/8/8/8/4RK2 w - - 0 1',
    moves: ['Re4'],
    rating: 900,
    themes: ['endgame', 'rook'],
    title: 'Rook Cutoff',
    description: 'Cut off the king.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p29',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2B1n3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    moves: ['Bxf7+', 'Ke7', 'd3'],
    rating: 950,
    themes: ['tactic', 'sacrifice'],
    title: 'Win Material',
    description: 'Win material with a sacrifice.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p30',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 6 5',
    moves: ['d3', 'd6', 'c3'],
    rating: 900,
    themes: ['opening', 'italian'],
    title: 'Italian Classical',
    description: 'Build a solid position.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p31',
    fen: 'rnbqkb1r/pp2pppp/2p2n2/3p4/2PP4/2N5/PP2PPPP/R1BQKBNR w KQkq - 0 4',
    moves: ['e3', 'e6', 'Bd3'],
    rating: 950,
    themes: ['opening', 'slav'],
    title: 'Slav Defense',
    description: 'Play the Slav Defense setup.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p32',
    fen: 'r1bqkb1r/pp1npppp/2p2n2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 2 5',
    moves: ['e3', 'e6', 'Bd3'],
    rating: 900,
    themes: ['opening', 'qgd'],
    title: 'QGD Setup',
    description: 'Set up the Queens Gambit Declined.',
    difficulty: 'medium',
    xpReward: 25,
  },
  // === HARD PUZZLES (Rating 1100-1400) ===
  {
    id: 'p33',
    fen: 'r1b1k2r/ppppqppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 4 5',
    moves: ['Ng5', 'O-O', 'Nxh7'],
    rating: 1150,
    themes: ['attack', 'sacrifice'],
    title: 'Knight Attack',
    description: 'Launch a kingside attack.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p34',
    fen: 'r1bq1rk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQ1RK1 w - - 0 7',
    moves: ['h3', 'h6', 'Be3'],
    rating: 1200,
    themes: ['strategy', 'prophylaxis'],
    title: 'Prophylaxis',
    description: 'Prevent threats while improving.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p35',
    fen: 'r1b2rk1/ppp2ppp/2n2n2/3qp3/3P4/2N2N2/PPP2PPP/R1BQ1RK1 w - - 0 9',
    moves: ['dxe5', 'Nxe5', 'Nxe5'],
    rating: 1250,
    themes: ['tactic', 'exchange'],
    title: 'Exchange and Win',
    description: 'Win material precisely.',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p36',
    fen: 'r1bq1rk1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQR1K1 w - - 0 8',
    moves: ['Nd5', 'Nxd5', 'exd5'],
    rating: 1300,
    themes: ['strategy', 'outpost'],
    title: 'Knight Jump',
    description: 'Control key squares.',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p37',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3p4/1bPP4/2N1PN2/PP3PPP/R1BQKB1R w KQ - 0 6',
    moves: ['a3', 'Bxc3+', 'bxc3'],
    rating: 1200,
    themes: ['strategy', 'bishopPair'],
    title: 'Bishop Pair',
    description: 'Win the bishop pair.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p38',
    fen: 'r1bq1rk1/pp1n1ppp/2pbpn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 8',
    moves: ['b4', 'a6', 'a4'],
    rating: 1350,
    themes: ['strategy', 'minorityAttack'],
    title: 'Minority Attack',
    description: 'Attack the queenside.',
    difficulty: 'hard',
    xpReward: 45,
  },
  {
    id: 'p39',
    fen: 'r1bq1rk1/pppn1ppp/4pn2/3p4/1bPP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 2 7',
    moves: ['cxd5', 'exd5', 'Qc2'],
    rating: 1300,
    themes: ['strategy', 'openLines'],
    title: 'Open Lines',
    description: 'Open lines for pieces.',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p40',
    fen: 'rnbqkb1r/pppppp1p/5np1/8/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3',
    moves: ['Nc3', 'Bg7', 'e4'],
    rating: 1200,
    themes: ['opening', 'kingsIndian'],
    title: 'Kings Indian',
    description: 'Face the Kings Indian Defense.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p41',
    fen: 'r2q1rk1/pp2ppbp/2np1np1/8/3NP3/2N1B3/PPPQBPPP/R3K2R w KQ - 0 9',
    moves: ['O-O-O', 'Qa5', 'f3'],
    rating: 1400,
    themes: ['attack', 'sicilian'],
    title: 'Sicilian Dragon',
    description: 'Set up your attack.',
    difficulty: 'hard',
    xpReward: 45,
  },
  // === EXPERT PUZZLES (Rating 1500-1800) ===
  {
    id: 'p42',
    fen: '2r3k1/5ppp/8/8/8/8/5PPP/2R3K1 w - - 0 1',
    moves: ['Rc4', 'Kf8', 'Ra4'],
    rating: 1500,
    themes: ['endgame', 'simplification'],
    title: 'Rook Endgame',
    description: 'Improve your rook position.',
    difficulty: 'expert',
    xpReward: 50,
  },
  {
    id: 'p43',
    fen: '8/8/8/8/8/5k2/5P2/5K2 w - - 0 1',
    moves: ['Ke1', 'Ke4', 'Ke2'],
    rating: 1550,
    themes: ['endgame', 'pawnEndgame'],
    title: 'Pawn Endgame',
    description: 'Navigate correctly.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p44',
    fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/3NP3/2N1B3/PPPQBPPP/R3K2R w KQ - 0 9',
    moves: ['O-O-O', 'a6', 'f3'],
    rating: 1600,
    themes: ['attack', 'oppositeCastling'],
    title: 'Opposite Castling',
    description: 'Castle queenside and attack.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p45',
    fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/2BNP3/2N1B3/PPP2PPP/R2QK2R w KQ - 0 8',
    moves: ['Qd2', 'a6', 'O-O-O'],
    rating: 1650,
    themes: ['opening', 'sicilian'],
    title: 'Dragon Setup',
    description: 'Set up the Yugoslav Attack.',
    difficulty: 'expert',
    xpReward: 60,
  },
  {
    id: 'p46',
    fen: '8/5pk1/8/8/8/8/5PP1/6K1 w - - 0 1',
    moves: ['f4', 'Kf6', 'Kf2'],
    rating: 1500,
    themes: ['endgame', 'kingActivity'],
    title: 'King Activity',
    description: 'Activate your king.',
    difficulty: 'expert',
    xpReward: 50,
  },
  {
    id: 'p47',
    fen: 'r1bq1rk1/pp1nppbp/2np2p1/8/2BNP3/2N1BP2/PPPQ2PP/R3K2R w KQ - 0 9',
    moves: ['O-O-O', 'a6', 'g4'],
    rating: 1700,
    themes: ['attack', 'pawnStorm'],
    title: 'Kingside Storm',
    description: 'Launch a pawn storm.',
    difficulty: 'expert',
    xpReward: 65,
  },
  {
    id: 'p48',
    fen: 'r1b2rk1/pp2ppbp/2np1np1/q7/2BNP3/2N1BP2/PPPQ2PP/R3K2R w KQ - 0 10',
    moves: ['O-O-O', 'Qc7', 'h4'],
    rating: 1750,
    themes: ['attack', 'sicilian'],
    title: 'Yugoslav Attack',
    description: 'Continue with precision.',
    difficulty: 'expert',
    xpReward: 70,
  },
  {
    id: 'p49',
    fen: 'r2qk2r/pp1nbppp/2p1pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQK2R w KQkq - 2 8',
    moves: ['Qc2', 'O-O', 'O-O'],
    rating: 1600,
    themes: ['opening', 'qgd'],
    title: 'QGD Classical',
    description: 'Navigate the Queens Gambit.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p50',
    fen: 'rnbqkb1r/pp2pppp/5n2/2pp4/2PP4/2N5/PP2PPPP/R1BQKBNR w KQkq d6 0 4',
    moves: ['cxd5', 'Nxd5', 'e4'],
    rating: 1650,
    themes: ['opening', 'panov'],
    title: 'Panov Attack',
    description: 'Play the aggressive Panov.',
    difficulty: 'expert',
    xpReward: 60,
  },
  {
    id: 'p51',
    fen: 'rnbqkb1r/pp2pppp/5n2/3p4/3P4/2N2N2/PPP1PPPP/R1BQKB1R w KQkq - 2 4',
    moves: ['Bg5', 'e6', 'e3'],
    rating: 1500,
    themes: ['opening', 'london'],
    title: 'London System',
    description: 'Set up the solid London.',
    difficulty: 'expert',
    xpReward: 50,
  },
  {
    id: 'p52',
    fen: 'rnbqkb1r/ppp1pppp/5n2/3p4/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3',
    moves: ['cxd5', 'Nxd5', 'e4'],
    rating: 1550,
    themes: ['opening', 'queensGambit'],
    title: 'Queens Gambit',
    description: 'Fight for the center.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p53',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    moves: ['Bb5', 'a6', 'Ba4'],
    rating: 1700,
    themes: ['opening', 'ruyLopez'],
    title: 'Ruy Lopez',
    description: 'Play the classical Ruy Lopez.',
    difficulty: 'expert',
    xpReward: 65,
  },
  // === NEW PUZZLES (p54-p65) ===
  {
    id: 'p54',
    fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    moves: ['Re8#'],
    rating: 400,
    themes: ['mate', 'backRank'],
    title: 'Back Rank Mate',
    description: 'The king is stuck behind its own pawns. Deliver the final blow!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p55',
    fen: 'r1bqkb1r/pppppppp/2n2n2/8/3NP3/8/PPP2PPP/RNBQKB1R w KQkq - 2 4',
    moves: ['Nxc6', 'bxc6'],
    rating: 450,
    themes: ['tactics', 'capture'],
    title: 'Simple Fork',
    description: 'Capture the knight and damage Black\'s pawn structure.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p56',
    fen: 'rnb1kbnr/pppppppp/8/8/4q3/2N5/PPPPPPPP/R1BQKBNR w KQkq - 0 1',
    moves: ['Nxe4'],
    rating: 500,
    themes: ['tactics', 'capture'],
    title: 'Queen Capture',
    description: 'Black\'s queen has wandered into danger. Win the queen!',
    difficulty: 'easy',
    xpReward: 15,
  },
  {
    id: 'p57',
    fen: '8/4P1k1/8/8/8/8/6K1/8 w - - 0 1',
    moves: ['e8=Q'],
    rating: 550,
    themes: ['endgame', 'promotion'],
    title: 'Pawn Promotion',
    description: 'Push the pawn to promotion and get a new queen!',
    difficulty: 'easy',
    xpReward: 15,
  },
  {
    id: 'p58',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4',
    moves: ['Nxe4', 'Bxf7+', 'Kf8'],
    rating: 750,
    themes: ['tactics', 'sacrifice', 'fork'],
    title: 'Knight Fork Royal',
    description: 'Win a pawn but watch out for the bishop counter-strike!',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p59',
    fen: 'r2qkbnr/ppp2ppp/2np4/4p3/2B1P1b1/5N2/PPPP1PPP/RNBQ1RK1 w kq - 2 5',
    moves: ['Bxf7+', 'Kd7'],
    rating: 800,
    themes: ['tactics', 'sacrifice', 'discoveredAttack'],
    title: 'Discovered Attack',
    description: 'Sacrifice the bishop to expose the enemy king!',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p60',
    fen: 'rnbqk2r/pppp1ppp/4pn2/8/1bPP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 2 4',
    moves: ['Qb3', 'Bxc3+', 'bxc3'],
    rating: 900,
    themes: ['tactics', 'pin', 'strategy'],
    title: 'Pin and Win',
    description: 'Use the queen to exploit the pin on the knight!',
    difficulty: 'medium',
    xpReward: 30,
  },
  {
    id: 'p61',
    fen: 'r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1',
    moves: ['Nc7+', 'Kd8', 'Nxa8'],
    rating: 950,
    themes: ['tactics', 'fork', 'endgame'],
    title: 'Knight Fork',
    description: 'Fork the king and rook with the knight!',
    difficulty: 'medium',
    xpReward: 30,
  },
  {
    id: 'p62',
    fen: 'r1bq1rk1/pppn1ppp/4pn2/3p4/1bPP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 8',
    moves: ['cxd5', 'exd5', 'Nxd5'],
    rating: 1200,
    themes: ['tactics', 'sacrifice', 'centerControl'],
    title: 'Greek Gift Sacrifice',
    description: 'Break open the center and win a pawn with a tactical sequence!',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p63',
    fen: 'r1b2rk1/pp3ppp/2n1pn2/q2p4/3P4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 9',
    moves: ['Nb5', 'Qd8', 'Nc7'],
    rating: 1350,
    themes: ['tactics', 'fork', 'knightOutpost'],
    title: 'Knight Outpost',
    description: 'Drive the queen away and plant the knight deep in enemy territory!',
    difficulty: 'hard',
    xpReward: 45,
  },
  {
    id: 'p64',
    fen: 'r2q1rk1/ppp1bppp/2n1pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 8',
    moves: ['cxd5', 'exd5', 'Nxd5', 'Nxd5', 'Bxh7+'],
    rating: 1550,
    themes: ['sacrifice', 'tactics', 'attack'],
    title: 'Positional Sacrifice',
    description: 'Exchange pieces to open lines and launch a devastating bishop sacrifice!',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p65',
    fen: 'r1bq1rk1/pp2bppp/2n1pn2/2pp4/2PP4/2N1PN2/PPB2PPP/R1BQ1RK1 w - - 0 8',
    moves: ['cxd5', 'exd5', 'dxc5', 'Bxc5', 'b4'],
    rating: 1700,
    themes: ['strategy', 'pawnStructure', 'opening'],
    title: 'Exchange Sacrifice',
    description: 'Open lines and gain a positional advantage with precise pawn play!',
    difficulty: 'expert',
    xpReward: 65,
  },
]

