import type { Trap } from '../chess-data'

export const TRAPS: Trap[] = [
  {
    id: 'legal-trap',
    name: "Legal's Trap",
    opening: 'Italian Game',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'd6', 'Nc3', 'Bg4', 'h3', 'Bh5', 'Nxe5', 'Bxd1', 'Bxf7+', 'Ke7', 'Nd5#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A classic trap where White sacrifices the queen to deliver a stunning checkmate.',
    explanation: [
      'White plays Nxe5 seemingly losing the queen to Bxd1',
      'But after Bxf7+ the king is forced to e7',
      'Then Nd5# delivers a beautiful checkmate',
      'The knight on e5, bishop on f7, and knight on d5 create an inescapable net'
    ],
    moveAnnotations: [
      'Standard opening',
      'Black mirrors',
      'Develops and attacks e5',
      'Defends e5',
      'Targets f7',
      'Supports e5 passively',
      'Develops naturally',
      'Pins the knight — this is the mistake!',
      'Asks the bishop a question',
      'Maintains the pin... but falls into the trap',
      'Sacrifice! Seemingly hangs the queen',
      'Black greedily takes the queen',
      'Check! The king must move',
      'Forced — only legal move',
      'Checkmate! The knights and bishop create a net',
    ],
    difficulty: 'beginner',
    side: 'white',
    xpReward: 30,
  },
  {
    id: 'stafford-gambit',
    name: 'Stafford Gambit',
    opening: 'Petrov Defense',
    moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'Nc6', 'Nxc6', 'dxc6', 'd3', 'Bc5', 'Bg5', 'Nxe4', 'Bxd8', 'Bxf2+', 'Ke2', 'Bg4#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A trappy gambit where Black sacrifices a pawn for a vicious attack.',
    explanation: [
      'Black plays Nc6 instead of the normal dxc6, offering a piece',
      'After dxc6, Black develops rapidly with Bc5 and sets up tactics',
      'The key idea is Bxf2+ forcing the king to e2',
      'Then Bg4# is a stunning checkmate'
    ],
    moveAnnotations: [
      'Standard opening',
      'Mirrors',
      'Attacks e5',
      'The Petrov — counter-attacks e4',
      'Takes the pawn',
      'The Stafford Gambit! Offering the knight',
      'White takes the bait',
      'Opens the d-file',
      'Tries to solidify',
      'Aims at f2 — the attack begins',
      'Tries to pin, but it\'s too late...',
      'Attacks the queen with tempo',
      'Takes the queen, thinking it\'s winning',
      'Check! Drags the king out',
      'Forced',
      'Checkmate! Beautiful bishop coordination',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'fried-liver',
    name: 'Fried Liver Attack',
    opening: 'Italian Game - Two Knights',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5', 'd5', 'exd5', 'Nxd5', 'Nxf7', 'Kxf7', 'Qf3+', 'Ke6', 'Nc3'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A devastating attack where White sacrifices a knight on f7 to drag the Black king into the center.',
    explanation: [
      'White plays the aggressive Ng5 targeting f7',
      'After d5 exd5 Nxd5, White strikes with Nxf7!',
      'The king is forced to take and enters a danger zone',
      'Qf3+ followed by Nc3 creates an overwhelming attack'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Italian Game setup',
      'Two Knights Defense',
      'The attack begins! Threatens Nxf7',
      'Black tries to counter in the center',
      'Captures',
      'Seems safe... but falls into the Fried Liver',
      'Knight sacrifice! Exposing the king',
      'Must accept',
      'Check! The king is dragged forward',
      'Walking into the fire',
      'Develops with tempo — devastating attack',
    ],
    difficulty: 'beginner',
    side: 'white',
    xpReward: 30,
  },
  {
    id: 'elephant-trap',
    name: 'Elephant Trap',
    opening: "Queen's Gambit Declined",
    moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Nbd7', 'cxd5', 'exd5', 'Nxd5', 'Nxd5', 'Bxd8', 'Bb4+', 'Qd2', 'Bxd2+', 'Kxd2', 'Kxd8'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A classic trap where Black wins material after White greedily captures the d5 pawn.',
    explanation: [
      'White plays cxd5 exd5, then greedily takes Nxd5',
      'Black responds Nxd5, and after Bxd8, plays the shocking Bb4+!',
      'White must block with Qd2, then Bxd2+ Kxd2 Kxd8',
      'Black has won a full piece!'
    ],
    moveAnnotations: [
      'Queen\'s pawn opening',
      'Symmetrical center',
      'The Queen\'s Gambit',
      'Declines',
      'Develops',
      'Develops',
      'Pins the knight',
      'Sets the trap — looks passive but...',
      'White exchanges',
      'Recaptures',
      'Greedy! This springs the trap',
      'Counter-capture',
      'Takes the queen — but...',
      'Surprise check! The real point',
      'Only move to block',
      'Takes with check again',
      'Forced recapture',
      'Black takes the bishop — net material gain!',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'lasker-trap',
    name: 'Lasker Trap',
    opening: "Queen's Gambit Accepted",
    moves: ['d4', 'd5', 'c4', 'dxc4', 'e3', 'b5', 'a4', 'c6', 'axb5', 'cxb5', 'Qf3'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'Named after Emanuel Lasker, this trap features sharp queenside play.',
    explanation: [
      'Black plays the tricky b5 trying to hold the c4 pawn',
      'White attacks with a4, and after the exchanges, plays Qf3',
      'This creates double threats on c6 and the a8 rook',
      'The key lesson is understanding pawn tension in the QGA'
    ],
    moveAnnotations: [
      'Queen\'s pawn',
      'Center control',
      'Queen\'s Gambit',
      'Accepts the gambit',
      'Plans to recapture the pawn',
      'Tricky! Holds onto the extra pawn',
      'Attacks the pawn chain',
      'Reinforces b5',
      'Captures',
      'Recaptures',
      'Forks the rook on a8 and threatens mate ideas',
    ],
    difficulty: 'intermediate',
    side: 'white',
    xpReward: 35,
  },
  {
    id: 'magnus-smith-trap',
    name: 'Magnus Smith Trap',
    opening: 'Sicilian Defense',
    moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'Nc6', 'Bc4', 'g6', 'Nxc6', 'bxc6', 'e5'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A sneaky trap in the Sicilian where White wins material with a powerful central thrust.',
    explanation: [
      'White develops naturally with Bc4 then plays the strong e5!',
      'This move attacks the d6 pawn and the f6 knight',
      'Black is forced into an awkward position',
      'White gains significant advantage'
    ],
    moveAnnotations: [
      'Standard',
      'Sicilian Defense',
      'Develops',
      'Supports e5',
      'Opens the center',
      'Exchanges',
      'Recaptures centrally',
      'Develops',
      'Develops',
      'Develops — but this allows the trap',
      'Targets f7',
      'Prepares fianchetto... but weakens',
      'Exchanges first',
      'Forced recapture',
      'The trap springs! Wins the d6 pawn or the knight',
    ],
    difficulty: 'advanced',
    side: 'white',
    xpReward: 50,
  },
  {
    id: 'blackburne-shilling',
    name: 'Blackburne Shilling Gambit',
    opening: 'Italian Game',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nd4', 'Nxe5', 'Qg5', 'Nxf7', 'Qxg2', 'Rf1', 'Qxe4+', 'Be2', 'Nf3#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A dangerous trap where Black sacrifices material for a smothered mate.',
    explanation: [
      'Black plays the unusual Nd4, seemingly a mistake',
      'If White takes on f7, Black plays Qg5 with threats',
      'After Qxg2 Rf1, Qxe4+ sets up the finale',
      'Nf3# is a beautiful smothered mate!'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Italian Game',
      'Unusual! Looks like a mistake',
      'Takes the free pawn — falling in!',
      'Attacks both the knight and g2',
      'Tries to counter-attack',
      'Takes the pawn with threats',
      'Defends f2',
      'Check! Forces the block',
      'Only move',
      'Smothered mate! Beautiful finish',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 45,
  },
  {
    id: 'englund-gambit',
    name: 'Englund Gambit Trap',
    opening: 'Englund Gambit',
    moves: ['d4', 'e5', 'dxe5', 'Nc6', 'Nf3', 'Qe7', 'Bf4', 'Qb4+', 'Bd2', 'Qxb2', 'Bc3', 'Bb4', 'Qd2', 'Bxc3', 'Qxc3', 'Qc1#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A surprise gambit where Black gives up material for a back rank mate.',
    explanation: [
      'Black gambits a pawn with e5 to create tactical chaos',
      'The key is Qb4+ forcing Bd2, then Qxb2 grabs a pawn',
      'After the sequence Bc3 Bb4, Black infiltrates',
      'Qc1# delivers checkmate on the back rank!'
    ],
    moveAnnotations: [
      'Standard',
      'The Englund Gambit — surprising!',
      'Takes the free pawn',
      'Develops with pressure',
      'Natural development',
      'Attacks the pawn and prepares tricks',
      'Defends e5',
      'Check! Forces a decision',
      'Blocks the check',
      'Grabs the b-pawn',
      'Tries to trap the queen',
      'Counter-pin!',
      'Tries to hold',
      'Takes the bishop',
      'Recaptures',
      'Back rank mate! Queen infiltrates',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'fishing-pole',
    name: 'Fishing Pole Trap',
    opening: 'Ruy Lopez',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6', 'O-O', 'Ng4', 'h3', 'h5', 'hxg4', 'hxg4', 'Ne1', 'Qh4', 'f4', 'g3', 'fxe5', 'Qh1#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A tricky trap in the Ruy Lopez where Black sacrifices a knight for a mating attack.',
    explanation: [
      'Black plays Ng4 offering the knight as bait',
      'If White takes hxg4 hxg4, the h-file opens dangerously',
      'Black follows with Qh4 creating threats',
      'The final Qh1# is unstoppable!'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Ruy Lopez',
      'Develops',
      'Castles',
      'The Fishing Pole! Offers the knight',
      'Attacks the knight',
      'Offers a piece sacrifice!',
      'Takes the bait',
      'Opens the h-file — deadly!',
      'Tries to retreat',
      'Queen joins the attack via the open file',
      'Tries to block',
      'Pawn advances with tempo',
      'Takes',
      'Checkmate on h1! The h-file is lethal',
    ],
    difficulty: 'advanced',
    side: 'black',
    xpReward: 50,
  },
  {
    id: 'noahs-ark',
    name: "Noah's Ark Trap",
    opening: 'Ruy Lopez',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'd6', 'd4', 'b5', 'Bb3', 'Nxd4', 'Nxd4', 'exd4', 'Qxd4', 'c5', 'Qd5', 'Be6', 'Qc6+', 'Bd7', 'Qd5', 'c4'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'An ancient trap where Black traps the White bishop on b3.',
    explanation: [
      'Black plays b5 and a6 to push the bishop back',
      'After the central exchanges, Black plays c5-c4',
      'The bishop on b3 is completely trapped',
      'This trap has been known since the 16th century!'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Ruy Lopez',
      'Morphy Defense',
      'Retreats',
      'Supports e5',
      'Opens the center',
      'Pushes the bishop further back',
      'Retreats again',
      'Captures the center pawn',
      'Recaptures',
      'Takes back',
      'Takes with the queen',
      'Attacks the queen and starts the trap',
      'Queen retreats',
      'Attacks the queen again',
      'Check — trying to escape',
      'Blocks',
      'Back again',
      'The bishop is trapped! Nowhere to go',
    ],
    difficulty: 'beginner',
    side: 'black',
    xpReward: 30,
  },
]

