import type { Trap } from '../chess-data'

export const TRAPS: Trap[] = [
  {
    id: 'legal-trap',
    name: "Legal's Trap",
    opening: 'Italian Game',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'd6', 'Nc3', 'Bg4', 'h3', 'Bh5', 'Nxe5', 'Bxd1', 'Bxf7+', 'Ke7', 'Nd5#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A classic trap where White sacrifices the queen to deliver a stunning checkmate.',
    explanation: [
      'White plays Nxe5 seemingly losing the queen to Bxd1',
      'But after Bxf7+ the king is forced to e7',
      'Then Nd5# delivers a beautiful checkmate',
      'The knight on e5, bishop on f7, and knight on d5 create an inescapable net'
    ],
    moveAnnotations: [
      'Standard opening',
      'Black mirrors',
      'Develops and attacks e5',
      'Defends e5',
      'Targets f7',
      'Supports e5 passively',
      'Develops naturally',
      'Pins the knight — this is the mistake!',
      'Asks the bishop a question',
      'Maintains the pin... but falls into the trap',
      'Sacrifice! Seemingly hangs the queen',
      'Black greedily takes the queen',
      'Check! The king must move',
      'Forced — only legal move',
      'Checkmate! The knights and bishop create a net',
    ],
    difficulty: 'beginner',
    side: 'white',
    xpReward: 30,
  },
  {
    id: 'stafford-gambit',
    name: 'Stafford Gambit',
    opening: 'Petrov Defense',
    moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'Nc6', 'Nxc6', 'dxc6', 'd3', 'Bc5', 'Bg5', 'Nxe4', 'Bxd8', 'Bxf2+', 'Ke2', 'Bg4#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A trappy gambit where Black sacrifices a pawn for a vicious attack.',
    explanation: [
      'Black plays Nc6 instead of the normal dxc6, offering a piece',
      'After dxc6, Black develops rapidly with Bc5 and sets up tactics',
      'The key idea is Bxf2+ forcing the king to e2',
      'Then Bg4# is a stunning checkmate'
    ],
    moveAnnotations: [
      'Standard opening',
      'Mirrors',
      'Attacks e5',
      'The Petrov — counter-attacks e4',
      'Takes the pawn',
      'The Stafford Gambit! Offering the knight',
      'White takes the bait',
      'Opens the d-file',
      'Tries to solidify',
      'Aims at f2 — the attack begins',
      'Tries to pin, but it\'s too late...',
      'Attacks the queen with tempo',
      'Takes the queen, thinking it\'s winning',
      'Check! Drags the king out',
      'Forced',
      'Checkmate! Beautiful bishop coordination',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'fried-liver',
    name: 'Fried Liver Attack',
    opening: 'Italian Game - Two Knights',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5', 'd5', 'exd5', 'Nxd5', 'Nxf7', 'Kxf7', 'Qf3+', 'Ke6', 'Nc3'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A devastating attack where White sacrifices a knight on f7 to drag the Black king into the center.',
    explanation: [
      'White plays the aggressive Ng5 targeting f7',
      'After d5 exd5 Nxd5, White strikes with Nxf7!',
      'The king is forced to take and enters a danger zone',
      'Qf3+ followed by Nc3 creates an overwhelming attack'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Italian Game setup',
      'Two Knights Defense',
      'The attack begins! Threatens Nxf7',
      'Black tries to counter in the center',
      'Captures',
      'Seems safe... but falls into the Fried Liver',
      'Knight sacrifice! Exposing the king',
      'Must accept',
      'Check! The king is dragged forward',
      'Walking into the fire',
      'Develops with tempo — devastating attack',
    ],
    difficulty: 'beginner',
    side: 'white',
    xpReward: 30,
  },
  {
    id: 'elephant-trap',
    name: 'Elephant Trap',
    opening: "Queen's Gambit Declined",
    moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Nbd7', 'cxd5', 'exd5', 'Nxd5', 'Nxd5', 'Bxd8', 'Bb4+', 'Qd2', 'Bxd2+', 'Kxd2', 'Kxd8'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A classic trap where Black wins material after White greedily captures the d5 pawn.',
    explanation: [
      'White plays cxd5 exd5, then greedily takes Nxd5',
      'Black responds Nxd5, and after Bxd8, plays the shocking Bb4+!',
      'White must block with Qd2, then Bxd2+ Kxd2 Kxd8',
      'Black has won a full piece!'
    ],
    moveAnnotations: [
      'Queen\'s pawn opening',
      'Symmetrical center',
      'The Queen\'s Gambit',
      'Declines',
      'Develops',
      'Develops',
      'Pins the knight',
      'Sets the trap — looks passive but...',
      'White exchanges',
      'Recaptures',
      'Greedy! This springs the trap',
      'Counter-capture',
      'Takes the queen — but...',
      'Surprise check! The real point',
      'Only move to block',
      'Takes with check again',
      'Forced recapture',
      'Black takes the bishop — net material gain!',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'lasker-trap',
    name: 'Lasker Trap',
    opening: "Queen's Gambit Accepted",
    moves: ['d4', 'd5', 'c4', 'dxc4', 'e3', 'b5', 'a4', 'c6', 'axb5', 'cxb5', 'Qf3'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'Named after Emanuel Lasker, this trap features sharp queenside play.',
    explanation: [
      'Black plays the tricky b5 trying to hold the c4 pawn',
      'White attacks with a4, and after the exchanges, plays Qf3',
      'This creates double threats on c6 and the a8 rook',
      'The key lesson is understanding pawn tension in the QGA'
    ],
    moveAnnotations: [
      'Queen\'s pawn',
      'Center control',
      'Queen\'s Gambit',
      'Accepts the gambit',
      'Plans to recapture the pawn',
      'Tricky! Holds onto the extra pawn',
      'Attacks the pawn chain',
      'Reinforces b5',
      'Captures',
      'Recaptures',
      'Forks the rook on a8 and threatens mate ideas',
    ],
    difficulty: 'intermediate',
    side: 'white',
    xpReward: 35,
  },
  {
    id: 'magnus-smith-trap',
    name: 'Magnus Smith Trap',
    opening: 'Sicilian Defense',
    moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'Nc6', 'Bc4', 'g6', 'Nxc6', 'bxc6', 'e5'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A sneaky trap in the Sicilian where White wins material with a powerful central thrust.',
    explanation: [
      'White develops naturally with Bc4 then plays the strong e5!',
      'This move attacks the d6 pawn and the f6 knight',
      'Black is forced into an awkward position',
      'White gains significant advantage'
    ],
    moveAnnotations: [
      'Standard',
      'Sicilian Defense',
      'Develops',
      'Supports e5',
      'Opens the center',
      'Exchanges',
      'Recaptures centrally',
      'Develops',
      'Develops',
      'Develops — but this allows the trap',
      'Targets f7',
      'Prepares fianchetto... but weakens',
      'Exchanges first',
      'Forced recapture',
      'The trap springs! Wins the d6 pawn or the knight',
    ],
    difficulty: 'advanced',
    side: 'white',
    xpReward: 50,
  },
  {
    id: 'blackburne-shilling',
    name: 'Blackburne Shilling Gambit',
    opening: 'Italian Game',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nd4', 'Nxe5', 'Qg5', 'Nxf7', 'Qxg2', 'Rf1', 'Qxe4+', 'Be2', 'Nf3#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A dangerous trap where Black sacrifices material for a smothered mate.',
    explanation: [
      'Black plays the unusual Nd4, seemingly a mistake',
      'If White takes on f7, Black plays Qg5 with threats',
      'After Qxg2 Rf1, Qxe4+ sets up the finale',
      'Nf3# is a beautiful smothered mate!'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Italian Game',
      'Unusual! Looks like a mistake',
      'Takes the free pawn — falling in!',
      'Attacks both the knight and g2',
      'Tries to counter-attack',
      'Takes the pawn with threats',
      'Defends f2',
      'Check! Forces the block',
      'Only move',
      'Smothered mate! Beautiful finish',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 45,
  },
  {
    id: 'englund-gambit',
    name: 'Englund Gambit Trap',
    opening: 'Englund Gambit',
    moves: ['d4', 'e5', 'dxe5', 'Nc6', 'Nf3', 'Qe7', 'Bf4', 'Qb4+', 'Bd2', 'Qxb2', 'Bc3', 'Bb4', 'Qd2', 'Bxc3', 'Qxc3', 'Qc1#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A surprise gambit where Black gives up material for a back rank mate.',
    explanation: [
      'Black gambits a pawn with e5 to create tactical chaos',
      'The key is Qb4+ forcing Bd2, then Qxb2 grabs a pawn',
      'After the sequence Bc3 Bb4, Black infiltrates',
      'Qc1# delivers checkmate on the back rank!'
    ],
    moveAnnotations: [
      'Standard',
      'The Englund Gambit — surprising!',
      'Takes the free pawn',
      'Develops with pressure',
      'Natural development',
      'Attacks the pawn and prepares tricks',
      'Defends e5',
      'Check! Forces a decision',
      'Blocks the check',
      'Grabs the b-pawn',
      'Tries to trap the queen',
      'Counter-pin!',
      'Tries to hold',
      'Takes the bishop',
      'Recaptures',
      'Back rank mate! Queen infiltrates',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'fishing-pole',
    name: 'Fishing Pole Trap',
    opening: 'Ruy Lopez',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6', 'O-O', 'Ng4', 'h3', 'h5', 'hxg4', 'hxg4', 'Ne1', 'Qh4', 'f4', 'g3', 'fxe5', 'Qh1#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A tricky trap in the Ruy Lopez where Black sacrifices a knight for a mating attack.',
    explanation: [
      'Black plays Ng4 offering the knight as bait',
      'If White takes hxg4 hxg4, the h-file opens dangerously',
      'Black follows with Qh4 creating threats',
      'The final Qh1# is unstoppable!'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Ruy Lopez',
      'Develops',
      'Castles',
      'The Fishing Pole! Offers the knight',
      'Attacks the knight',
      'Offers a piece sacrifice!',
      'Takes the bait',
      'Opens the h-file — deadly!',
      'Tries to retreat',
      'Queen joins the attack via the open file',
      'Tries to block',
      'Pawn advances with tempo',
      'Takes',
      'Checkmate on h1! The h-file is lethal',
    ],
    difficulty: 'advanced',
    side: 'black',
    xpReward: 50,
  },
  {
    id: 'noahs-ark',
    name: "Noah's Ark Trap",
    opening: 'Ruy Lopez',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'd6', 'd4', 'b5', 'Bb3', 'Nxd4', 'Nxd4', 'exd4', 'Qxd4', 'c5', 'Qd5', 'Be6', 'Qc6+', 'Bd7', 'Qd5', 'c4'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'An ancient trap where Black traps the White bishop on b3.',
    explanation: [
      'Black plays b5 and a6 to push the bishop back',
      'After the central exchanges, Black plays c5-c4',
      'The bishop on b3 is completely trapped',
      'This trap has been known since the 16th century!'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Ruy Lopez',
      'Morphy Defense',
      'Retreats',
      'Supports e5',
      'Opens the center',
      'Pushes the bishop further back',
      'Retreats again',
      'Captures the center pawn',
      'Recaptures',
      'Takes back',
      'Takes with the queen',
      'Attacks the queen and starts the trap',
      'Queen retreats',
      'Attacks the queen again',
      'Check — trying to escape',
      'Blocks',
      'Back again',
      'The bishop is trapped! Nowhere to go',
    ],
    difficulty: 'beginner',
    side: 'black',
    xpReward: 30,
  },
  {
    id: 'cambridge-springs',
    name: 'Cambridge Springs Trap',
    opening: "Queen's Gambit Declined",
    moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Nbd7', 'Nf3', 'c6', 'e3', 'Qa5', 'Nd2', 'Bb4', 'Qc2', 'O-O', 'Bd3', 'dxc4', 'Bxc4', 'Nd5'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A famous trap from the QGD where Black pins the knight and creates tactical threats.',
    explanation: [
      'Black develops Qa5 pinning the Nc3 to the king',
      'Combined with Bb4, this creates a double pin',
      'Black wins material or achieves a dominant position',
      'The Nd5 forks multiple pieces after the pawn exchange'
    ],
    moveAnnotations: [
      'Standard QGD opening', 'Mirrors', 'Offers the gambit', 'Declines',
      'Develops knight', 'Natural development', 'Pins the knight', 'Develops behind pawns',
      'Standard', 'Prepares Qa5', 'Supports center', 'The Cambridge Springs move!',
      'Retreats the knight', 'Pins another piece', 'Unpins', 'Castles safely',
      'Develops bishop', 'Opens the center', 'Recaptures', 'Powerful centralized knight'
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 35,
  },
  {
    id: 'mortimer-trap',
    name: 'Mortimer Trap',
    opening: 'Ruy Lopez',
    moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'd6', 'Nf3', 'Nxe4', 'd3', 'Nf6', 'd4', 'd5', 'Bd3', 'Bd6', 'O-O', 'O-O', 'Nc3', 'Bg4'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A positional trap where Black equalizes quickly and pins the knight for lasting pressure.',
    explanation: [
      'Black counter-attacks with Nf6 in the Petrov Defense',
      'After Nxe4 and d3, Black retreats and builds a solid position',
      'Bg4 pins the f3 knight, creating lasting pressure',
      'Black achieves a comfortable, active position'
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 35,
  },
  {
    id: 'siberian-trap',
    name: 'Siberian Trap',
    opening: 'Smith-Morra Gambit',
    moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Nf3', 'Bb4', 'Bg5', 'dxc4', 'e4', 'c5', 'Bxc4', 'cxd4', 'Nxd4', 'Qa5'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A cunning trap where Black wins material with a queen attack.',
    explanation: [
      'Black plays Bb4 pinning the knight early',
      'After taking on c4 and d4, Black opens the position',
      'Qa5 attacks the pinned knight and the bishop on g5',
      'White cannot defend both pieces simultaneously'
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 35,
  },
  {
    id: 'tarrasch-trap',
    name: 'Tarrasch Trap',
    opening: 'Ruy Lopez',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Nxe4', 'd4', 'b5', 'Bb3', 'd5', 'dxe5', 'Be6', 'c3', 'Bc5', 'Nbd2', 'O-O'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A classical trap in the Ruy Lopez Open Defense where Black gets excellent piece activity.',
    explanation: [
      'Black takes on e4 in the Open Ruy Lopez',
      'After d5, Black gets strong central pawns',
      'Be6 and Bc5 create pressure on f2',
      'Black achieves active piece play with a dangerous initiative'
    ],
    difficulty: 'advanced',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'caro-kann-smothered',
    name: 'Caro-Kann Smothered Mate',
    opening: 'Caro-Kann Defense',
    moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Nd7', 'Qe2', 'Ngf6', 'Nd6#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A devastating smothered mate in the Caro-Kann where White delivers checkmate on move 6!',
    explanation: [
      'Black develops Nd7 and Ngf6 blocking the king escape squares',
      'Qe2 prevents the king from fleeing to e7',
      'Nd6# is checkmate — the king is surrounded by its own pieces',
      'One of the fastest possible checkmates in the Caro-Kann'
    ],
    moveAnnotations: [
      'Standard opening', 'The Caro-Kann', 'Advances center', 'Challenges center',
      'Develops knight', 'Takes', 'Recaptures centrally', 'Develops — but blocks the king!',
      'Crucial! Controls e7', 'Develops — sealed in!', 'Smothered checkmate!'
    ],
    difficulty: 'beginner',
    side: 'white',
    xpReward: 30,
  },
  {
    id: 'petroff-trap',
    name: 'Petroff Trap',
    opening: 'Petrov Defense',
    moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'Nxe4', 'Qe2', 'Nf6', 'Nc6+', 'Be7', 'Nxd8', 'Kxd8'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A trap where White wins the queen by exploiting the knight on e5.',
    explanation: [
      'After Nxe5 Nxe4, White plays the tricky Qe2',
      'Black retreats Nf6, but Nc6+ is a discovered attack',
      'The knight on c6 attacks the queen with check',
      'White wins the black queen for a knight'
    ],
    difficulty: 'beginner',
    side: 'white',
    xpReward: 30,
  },
  {
    id: 'philidor-trap',
    name: 'Philidor Trap',
    opening: 'Philidor Defense',
    moves: ['e4', 'e5', 'Nf3', 'd6', 'Bc4', 'Bg4', 'Nc3', 'g6', 'Nxe5', 'Bxd1', 'Bxf7+', 'Ke7', 'Nd5#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A queen sacrifice leading to a spectacular checkmate with minor pieces.',
    explanation: [
      'White sacrifices the queen with Nxe5, inviting Bxd1',
      'Bxf7+ forces the king to e7',
      'Nd5# is checkmate — the two knights and bishop create a net',
      'Similar to Legal\'s Trap but from the Philidor Defense'
    ],
    moveAnnotations: [
      'Standard', 'The Philidor', 'Develops', 'Attacks f7',
      'Pins the knight — mistake!', 'Develops but weakens dark squares', 'Aggressive',
      'Nxe5 threatens queen and f7', 'Black greedily takes the queen',
      'Bishop sacrifice with check', 'Forced king move', 'Checkmate!'
    ],
    difficulty: 'beginner',
    side: 'white',
    xpReward: 30,
  },
  {
    id: 'budapest-trap',
    name: 'Budapest Gambit Trap',
    opening: 'Budapest Gambit',
    moves: ['d4', 'Nf6', 'c4', 'e5', 'dxe5', 'Ng4', 'Bf4', 'Nc6', 'Nf3', 'Bb4+', 'Nbd2', 'Qe7', 'a3', 'Ngxe5', 'axb4', 'Nd3#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A devastating smothered mate trap from the Budapest Gambit.',
    explanation: [
      'Black sacrifices the bishop with Bb4+ and Qe7',
      'White takes the bishop with axb4',
      'But Ngxe5 opens the path for Nd3#',
      'Nd3 is smothered checkmate — the king is trapped by its own pieces'
    ],
    moveAnnotations: [
      'Standard', 'Indian setup', 'Natural', 'The Budapest!',
      'Accepts the gambit', 'Knight attacks e5 and f2', 'Develops with defense',
      'Counterattack on e5', 'Develops', 'Check! Creating a battery',
      'Blocks', 'Prepares the trap', 'Takes the bishop — fatal error!',
      'Recaptures and threatens', 'Takes bishop anyway', 'Smothered checkmate!'
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 35,
  },
  {
    id: 'albin-counter',
    name: 'Albin Countergambit Trap',
    opening: 'Albin Countergambit',
    moves: ['d4', 'd5', 'c4', 'e5', 'dxe5', 'd4', 'e3', 'Bb4+', 'Bd2', 'dxe3', 'Bxb4', 'exf2+', 'Ke2', 'fxg1=N+', 'Ke1', 'Qh4+'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A wild trap featuring an underpromotion to knight with devastating effect.',
    explanation: [
      'Black pushes d4 creating a dangerous passed pawn',
      'After exchanges, the pawn reaches f2 with check',
      'fxg1=N+ is a brilliant underpromotion to knight with check!',
      'Qh4+ follows with a crushing attack'
    ],
    moveAnnotations: [
      'Standard', 'Mirrors', 'QG', 'The Albin Counter!',
      'Accepts', 'Dangerous passed pawn', 'Tries to block',
      'Check!', 'Blocks', 'Pawn storms forward', 'Takes bishop',
      'Pawn promotes with check!', 'Forced', 'Underpromotion to knight with check!',
      'Forced king move', 'Crushing check — the attack continues'
    ],
    difficulty: 'advanced',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'halosar-trap',
    name: 'Halosar Trap',
    opening: 'Blackmar-Diemer Gambit',
    moves: ['d4', 'd5', 'e4', 'dxe4', 'Nc3', 'Nf6', 'f3', 'exf3', 'Qxf3', 'Qxd4', 'Be3', 'Qb4', 'O-O-O', 'Bg4', 'Nb5', 'Bxf3', 'Nxc7#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A brilliant queen sacrifice leading to checkmate with a knight fork.',
    explanation: [
      'White gambits multiple pawns for rapid development',
      'When Black grabs the queen on f3, it removes a defender',
      'Nb5 threatens Nxc7+ and the queen simultaneously',
      'Nxc7# is checkmate — the knight, rook, and bishop control all escape squares'
    ],
    moveAnnotations: [
      'Gambit opening', 'Accepts', 'Gambit continues', 'Develops',
      'Recaptures', 'Takes pawn', 'Attacks queen', 'Takes pawn — greedy!',
      'Queen retreats', 'Develops with attack', 'Castles queenside — powerful',
      'Pins the queen? Not quite...', 'Attacks c7 and queen!',
      'Takes the queen!', 'Takes the queen — but...', 'Checkmate!'
    ],
    difficulty: 'intermediate',
    side: 'white',
    xpReward: 35,
  },
  {
    id: 'scotch-trap',
    name: 'Scotch Game Trap',
    opening: 'Scotch Game',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Nf6', 'Nc3', 'Bb4', 'Nxc6', 'bxc6', 'Bd3', 'd5', 'exd5', 'cxd5', 'O-O', 'O-O', 'Bg5', 'c6'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A positional trap in the Scotch where Black gets a strong pawn center and active pieces.',
    explanation: [
      'Black develops Bb4 pinning the knight aggressively',
      'After exchanges, Black achieves a strong pawn center with d5',
      'The bishop pair and central pawns give Black excellent play',
      'c6 solidifies the center, completing a harmonious setup'
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 35,
  },
  {
    id: 'vienna-trap',
    name: 'Vienna Game Trap',
    opening: 'Vienna Game',
    moves: ['e4', 'e5', 'Nc3', 'Nf6', 'f4', 'd5', 'fxe5', 'Nxe4', 'Nf3', 'Bg4', 'Qe2', 'Nc5', 'd4', 'Bxf3', 'Qxf3', 'Ne6'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A counter-attacking trap where Black turns the Vienna Gambit against White.',
    explanation: [
      'Black plays d5 challenging the center immediately',
      'Nxe4 grabs the pawn with tempo',
      'Bg4 pins the knight creating tactical threats',
      'Ne6 blockades the e-pawn and targets d4 and f4'
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 35,
  },
  {
    id: 'kings-gambit-trap',
    name: "King's Gambit Trap",
    opening: "King's Gambit",
    moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'g5', 'h4', 'g4', 'Ne5', 'Nf6', 'Bc4', 'd5', 'exd5', 'Bd6', 'd4', 'Nh5'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A trap where Black counter-attacks in the King\'s Gambit with piece activity.',
    explanation: [
      'Black advances g5-g4 pushing the knight away',
      'Ne5 looks strong but Black develops rapidly',
      'Bd6 attacks the knight on e5',
      'Nh5 eyes f4 and g3, preparing a kingside attack'
    ],
    difficulty: 'advanced',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'dutch-defense-trap',
    name: 'Dutch Defense Trap',
    opening: 'Dutch Defense',
    moves: ['d4', 'f5', 'Bg5', 'h6', 'Bh4', 'g5', 'Bg3', 'f4', 'e3', 'h5', 'Bd3', 'Rh6', 'Qxh5+', 'Rxh5', 'Bg6#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A spectacular queen sacrifice leading to a rare bishop checkmate.',
    explanation: [
      'White provokes Black into weakening the kingside with h6 and g5',
      'The bishop retreats to g3, then the d3 diagonal opens up',
      'Qxh5+! sacrifices the queen, and Black is forced to take with the rook',
      'Bg6# is a stunning checkmate — the bishop delivers mate on g6!'
    ],
    moveAnnotations: [
      'Standard', 'The Dutch', 'Unusual bishop sortie', 'Chases the bishop',
      'Retreats', 'Overextends!', 'Safe', 'Attacks the bishop',
      'Opens lines', 'Weakens further', 'Lines up on h7', 'Defensive move',
      'Queen sacrifice!', 'Forced recapture', 'Bishop checkmate!'
    ],
    difficulty: 'intermediate',
    side: 'white',
    xpReward: 35,
  },
]

