// Comprehensive chess learning data: openings, puzzles, traps

export interface Opening {
  id: string
  name: string
  eco: string
  moves: string[]
  fen: string
  description: string
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  category: 'e4' | 'd4' | 'other'
  popularity: number
  winRate: { white: number; draw: number; black: number }
  keyIdeas: string[]
  moveAnnotations?: string[]
  variations: { name: string; moves: string[]; description: string }[]
  learned?: boolean
}

export interface Puzzle {
  id: string
  fen: string
  moves: string[] // alternating: opponent move, your move, opponent response, your move...
  rating: number
  themes: string[]
  title: string
  description: string
  difficulty: 'easy' | 'medium' | 'hard' | 'expert'
  xpReward: number
  solved?: boolean
}

export interface Trap {
  id: string
  name: string
  opening: string
  moves: string[]
  fen: string
  description: string
  explanation: string[]
  moveAnnotations?: string[]
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  side: 'white' | 'black'
  xpReward: number
  learned?: boolean
}

export const OPENINGS: Opening[] = [
  {
    id: 'italian-game',
    name: 'Italian Game',
    eco: 'C50',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'd3', 'Nf6', 'O-O', 'O-O', 'c3', 'd6', 'Bb3', 'Be6', 'Nbd2', 'Bxb3', 'Qxb3', 'Qd7', 'Re1', 'a6', 'Nf1', 'Ba7', 'Ng3', 'Rab8', 'h3', 'h6', 'Be3', 'Bxe3', 'Rxe3', 'Rfe8', 'Rae1'],
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3',
    description: 'One of the oldest and most popular openings. White develops the bishop to c4 targeting the f7 square, the weakest point in Black\'s position.',
    difficulty: 'beginner',
    category: 'e4',
    popularity: 92,
    winRate: { white: 38, draw: 30, black: 32 },
    keyIdeas: [
      'Control the center with e4 and d4',
      'Target the weak f7 pawn',
      'Rapid piece development',
      'Prepare for kingside castling'
    ],
    moveAnnotations: [
      'Controls the center and opens diagonals for bishop and queen',
      'Mirrors White\'s central control',
      'Develops knight and attacks the e5 pawn',
      'Defends the e5 pawn with a knight',
      'Targets the weak f7 square near Black\'s king',
      'Develops actively, mirrors White\'s bishop placement',
      'Supports the e4 pawn and opens the bishop diagonal',
      'Develops the knight and attacks e4',
      'Castles kingside for king safety',
      'Black also castles for safety',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Giuoco Piano', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'd3', 'Nf6', 'O-O', 'O-O', 'Re1', 'a6', 'a4', 'Ba7', 'Nbd2', 'd6', 'Nf1'], description: 'The quiet game - solid and classical development' },
      { name: 'Evans Gambit', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'b4', 'Bxb4', 'c3', 'Ba5', 'd4', 'exd4', 'O-O', 'Nf6', 'cxd4'], description: 'Aggressive pawn sacrifice for rapid development and open lines' },
      { name: 'Two Knights Defense', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'd3', 'Be7', 'O-O', 'O-O', 'Re1', 'd6', 'c3', 'Na5', 'Bb5', 'c6', 'Bc4', 'Nxc4', 'dxc4'], description: 'Black counterattacks the e4 pawn immediately, leading to sharp play' },
      { name: 'Fried Liver Attack', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5', 'd5', 'exd5', 'Nxd5', 'Nxf7', 'Kxf7', 'Qf3+', 'Ke6', 'Nc3'], description: 'Sacrificing a knight for a devastating attack on the exposed king' },
    ]
  },
  {
    id: 'sicilian-defense',
    name: 'Sicilian Defense',
    eco: 'B20',
    moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be3', 'e5', 'Nb3', 'Be6', 'f3', 'Be7', 'Qd2', 'O-O', 'O-O-O', 'Nbd7', 'g4', 'b5', 'g5', 'Nh5', 'Kb1', 'Nb6', 'Na5', 'Rc8', 'Rg1', 'Nc4', 'Nxc4', 'bxc4'],
    fen: 'rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2',
    description: 'The most popular and best-scoring response to e4. Black fights for the center asymmetrically, leading to sharp tactical play.',
    difficulty: 'intermediate',
    category: 'e4',
    popularity: 97,
    winRate: { white: 35, draw: 28, black: 37 },
    keyIdeas: [
      'Asymmetrical pawn structure creates imbalance',
      'Black gains a queenside pawn majority',
      'Rich tactical and strategic possibilities',
      'Multiple sharp variations to study'
    ],
    moveAnnotations: [
      'Claims the center',
      'The Sicilian! Fights for d4 without mirroring',
      'Develops and prepares d4',
      'Supports the e5 square',
      'Opens the center',
      'Captures, giving Black a queenside majority',
      'Recaptures with development',
      'Develops and pressures e4',
      'Defends e4 and develops',
      'The Najdorf! Prevents Nb5 and prepares b5 expansion',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Najdorf', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be3', 'e5', 'Nb3', 'Be6', 'f3', 'h5', 'Qd2', 'Nbd7', 'O-O-O', 'Rc8'], description: 'The king of Sicilian variations - Bobby Fischer\'s weapon of choice' },
      { name: 'Dragon', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6', 'Be3', 'Bg7', 'f3', 'O-O', 'Qd2', 'Nc6', 'Bc4', 'Bd7', 'O-O-O', 'Rc8'], description: 'Fianchetto the bishop for a fire-breathing kingside attack' },
      { name: 'Classical', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'Nc6', 'Bg5', 'e6', 'Qd2', 'a6', 'O-O-O', 'Bd7', 'f4', 'Be7'], description: 'Solid development with piece pressure on the center' },
      { name: 'Sveshnikov', moves: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e5', 'Ndb5', 'd6', 'Bg5', 'a6', 'Na3', 'b5', 'Nd5', 'Be7', 'Bxf6', 'Bxf6'], description: 'Modern aggressive system accepting a backward d6 pawn for active play' },
    ]
  },
  {
    id: 'french-defense',
    name: 'French Defense',
    eco: 'C00',
    moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Nf6', 'Bg5', 'Be7', 'e5', 'Nfd7', 'Bxe7', 'Qxe7', 'f4', 'a6', 'Nf3', 'c5', 'dxc5', 'Nc6', 'Qd2', 'Qxc5', 'O-O-O', 'b5', 'Bd3', 'Bb7', 'Kb1', 'Rc8', 'Ne2', 'Nb6', 'Ned4', 'Nc4', 'Bxc4', 'bxc4', 'Nxc6', 'Bxc6'],
    fen: 'rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
    description: 'A solid defense where Black builds a strong pawn chain. It leads to strategic positions with clear plans for both sides.',
    difficulty: 'intermediate',
    category: 'e4',
    popularity: 78,
    winRate: { white: 37, draw: 32, black: 31 },
    keyIdeas: [
      'Solid pawn structure with e6-d5',
      'Counter-attack on the queenside with c5',
      'The light-squared bishop can be problematic',
      'Strategic maneuvering and pawn breaks'
    ],
    moveAnnotations: [
      'Claims central space',
      'Solid — prepares d5 while keeping the position closed',
      'Full center control',
      'Challenges White\'s center directly',
      'Develops and supports e4',
      'Increases pressure on e4',
      'Pins the knight to the queen',
      'Breaks the pin',
      'Gains space and restricts Black\'s knight',
      'Retreats but prepares f6 counterplay',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Winawer', moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Bb4', 'e5', 'c5', 'a3', 'Bxc3+', 'bxc3', 'Ne7', 'Qg4', 'Qc7', 'Qxg7', 'Rg8', 'Qxh7', 'cxd4'], description: 'Sharp and double-edged - pins the knight and provokes weaknesses' },
      { name: 'Advance', moves: ['e4', 'e6', 'd4', 'd5', 'e5', 'c5', 'c3', 'Nc6', 'Nf3', 'Qb6', 'a3', 'c4', 'Nbd2', 'Na5', 'Be2', 'Bd7', 'O-O', 'Ne7'], description: 'White grabs space with e5, Black attacks the pawn chain' },
      { name: 'Tarrasch', moves: ['e4', 'e6', 'd4', 'd5', 'Nd2', 'Nf6', 'e5', 'Nfd7', 'Bd3', 'c5', 'c3', 'Nc6', 'Ne2', 'cxd4', 'cxd4', 'f6', 'exf6', 'Nxf6'], description: 'Flexible system avoiding the Winawer pin, maintains pawn tension' },
      { name: 'Classical', moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Nf6', 'Bg5', 'Be7', 'e5', 'Nfd7', 'Bxe7', 'Qxe7', 'f4', 'O-O', 'Nf3', 'c5', 'Qd2', 'Nc6', 'O-O-O', 'a6'], description: 'The main line - strategic battle over the pawn chain' },
    ]
  },
  {
    id: 'ruy-lopez',
    name: 'Ruy Lopez',
    eco: 'C60',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'd6', 'c3', 'O-O', 'h3', 'Nb8', 'd4', 'Nbd7', 'Nbd2', 'Bb7', 'Bc2', 'Re8', 'Nf1', 'Bf8', 'Ng3', 'g6', 'a4', 'c5', 'd5', 'c4', 'Bg5', 'h6', 'Be3', 'Nc5', 'Qd2', 'Qc7'],
    fen: 'r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3',
    description: 'The Spanish Opening - one of the most respected and played openings at all levels. It creates long-term strategic pressure.',
    difficulty: 'intermediate',
    category: 'e4',
    popularity: 90,
    winRate: { white: 39, draw: 31, black: 30 },
    keyIdeas: [
      'Pressure on the e5 pawn through the c6 knight',
      'Long-term strategic advantage for White',
      'Rich middlegame plans',
      'Can lead to both open and closed positions'
    ],
    moveAnnotations: [
      'Central control',
      'Symmetrical center',
      'Attacks e5',
      'Defends e5',
      'The Ruy Lopez! Puts pressure on the knight defending e5',
      'Kicks the bishop — the Morphy Defense',
      'Maintains the pin on the knight',
      'Develops and counter-attacks e4',
      'Castles and connects the rooks',
      'Prepares to castle kingside',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Morphy Defense', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'd6', 'c3', 'O-O', 'h3', 'Na5', 'Bc2', 'c5', 'd4'], description: 'The main line - challenging the bishop immediately, leading to complex play' },
      { name: 'Berlin Defense', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6', 'O-O', 'Nxe4', 'd4', 'Nd6', 'Bxc6', 'dxc6', 'dxe5', 'Nf5', 'Qxd8+', 'Kxd8', 'Nc3', 'Ke8'], description: 'The Berlin Wall - ultra-solid endgame approach favored by Kramnik' },
      { name: 'Marshall Attack', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'O-O', 'c3', 'd5', 'exd5', 'Nxd5', 'd4', 'exd4', 'Re1', 'Be6'], description: 'A brilliant pawn sacrifice for a devastating attack - Black gives up a pawn for initiative' },
      { name: 'Closed Ruy Lopez', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'd6', 'c3', 'O-O', 'h3', 'Na5', 'Bc2', 'c5', 'd4', 'Qc7', 'Nbd2', 'Bd7'], description: 'Strategic maneuvering with slow buildup - a chess marathon' },
    ]
  },
  {
    id: 'queens-gambit',
    name: 'Queen\'s Gambit',
    eco: 'D06',
    moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Be7', 'e3', 'O-O', 'Nf3', 'Nbd7', 'Rc1', 'c6', 'Bd3', 'dxc4', 'Bxc4', 'Nd5', 'Bxe7', 'Qxe7', 'O-O', 'Nxc3', 'Rxc3', 'e5', 'dxe5', 'Nxe5', 'Nxe5', 'Qxe5', 'f3', 'Bf5', 'Qb3', 'Rfd8', 'Rf2', 'Rd7', 'Qxb7', 'Rad8'],
    fen: 'rnbqkbnr/ppp1pppp/8/3p4/2PP4/8/PP2PPPP/RNBQKBNR b KQkq c3 0 2',
    description: 'One of the oldest known openings. White offers a pawn to gain control of the center. It\'s not a true gambit as the pawn can usually be recovered.',
    difficulty: 'beginner',
    category: 'd4',
    popularity: 88,
    winRate: { white: 40, draw: 32, black: 28 },
    keyIdeas: [
      'Control the center with d4 and c4',
      'Open lines for piece development',
      'Create pressure on d5',
      'Strategic middlegame with clear plans'
    ],
    moveAnnotations: [
      'Controls the center with the d-pawn',
      'Meets the center head-on',
      'The Queen\'s Gambit — offers a pawn to control d5',
      'Declines the gambit, supporting d5',
      'Develops and increases pressure on d5',
      'Develops and defends d5',
      'Pins the knight to the queen',
      'Breaks the pin',
      'Solidifies the center',
      'Castles for safety',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Accepted', moves: ['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'Nf6', 'e3', 'e6', 'Bxc4', 'c5', 'O-O', 'a6', 'Qe2', 'b5', 'Bb3', 'Bb7', 'Rd1', 'Nbd7'], description: 'Black takes the pawn but must return it for solid development' },
      { name: 'Declined', moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Be7', 'e3', 'O-O', 'Nf3', 'Nbd7', 'Rc1', 'c6', 'Bd3', 'dxc4', 'Bxc4'], description: 'The classical solid response - Black maintains the center' },
      { name: 'Slav Defense', moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4', 'a4', 'Bf5', 'e3', 'e6', 'Bxc4', 'Bb4', 'O-O', 'O-O'], description: 'Supports d5 while keeping the light-squared bishop active on f5' },
      { name: 'Semi-Slav', moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'e6', 'e3', 'Nbd7', 'Bd3', 'dxc4', 'Bxc4', 'b5', 'Bd3', 'Bb7'], description: 'Flexible setup allowing both ...c5 and ...e5 breaks' },
      { name: 'Ragozin Defense', moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Nf3', 'Bb4', 'Bg5', 'dxc4', 'e4', 'c5', 'Bxc4', 'cxd4', 'Nxd4', 'Qa5'], description: 'Nimzo-Indian style with ...Bb4 creating tactical possibilities' },
    ]
  },
  {
    id: 'kings-indian',
    name: 'King\'s Indian Defense',
    eco: 'E60',
    moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2', 'e5', 'O-O', 'Nc6', 'd5', 'Ne7', 'Ne1', 'Nd7', 'f3', 'f5', 'Be3', 'f4', 'Bf2', 'g5', 'Nd3', 'Ng6', 'c5', 'Nf6', 'Rc1', 'Rf7', 'cxd6', 'cxd6', 'Nb5', 'h5'],
    fen: 'rnbqkb1r/pppppp1p/5np1/8/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3',
    description: 'A hypermodern defense where Black allows White to build a large center, then strikes back with devastating counterattacks.',
    difficulty: 'advanced',
    category: 'd4',
    popularity: 82,
    winRate: { white: 37, draw: 28, black: 35 },
    keyIdeas: [
      'Let White build the center, then destroy it',
      'Kingside attack with f5 and g5 pushes',
      'Dynamic piece play and tactical fireworks',
      'Rich strategic and tactical possibilities'
    ],
    moveAnnotations: [
      'Controls the center',
      'Flexible development, doesn\'t commit pawns yet',
      'Expands in the center',
      'The King\'s Indian! Prepares the fianchetto',
      'Develops naturally',
      'The fianchettoed bishop eyes the long diagonal',
      'Full center — White has a space advantage',
      'Supports e5 counterplay',
      'Completes development',
      'Castles, preparing the f5 pawn storm',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Classical', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2', 'e5', 'O-O', 'Nc6', 'd5', 'Ne7', 'Ne1', 'Nd7', 'Nd3', 'f5', 'f3', 'f4'], description: 'The main battleground with opposite-side attacks and closed center' },
      { name: 'Samisch', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'f3', 'O-O', 'Be3', 'e5', 'd5', 'Nh5', 'Qd2', 'f5', 'O-O-O', 'Nd7'], description: 'White builds a massive pawn center and often castles queenside' },
      { name: 'Four Pawns Attack', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'f4', 'O-O', 'Nf3', 'c5', 'd5', 'e6', 'Be2', 'exd5', 'cxd5', 'Bg4'], description: 'Aggressive - White pushes all four center pawns but can become overextended' },
      { name: 'Fianchetto System', moves: ['d4', 'Nf6', 'c4', 'g6', 'g3', 'Bg7', 'Bg2', 'O-O', 'Nc3', 'd6', 'Nf3', 'Nbd7', 'O-O', 'e5', 'e4', 'c6', 'h3', 'Qb6'], description: 'Calm approach where White also fianchettoes, leading to strategic battles' },
    ]
  },
  {
    id: 'london-system',
    name: 'London System',
    eco: 'D02',
    moves: ['d4', 'd5', 'Bf4', 'Nf6', 'e3', 'c5', 'c3', 'Nc6', 'Nd2', 'e6', 'Ngf3', 'Bd6', 'Bg3', 'O-O', 'Bd3', 'Qe7', 'Ne5', 'Nd7', 'Ndf3', 'f6', 'Nxd7', 'Bxd7', 'Bxd6', 'Qxd6', 'O-O', 'Rac8', 'Re1', 'Rf7', 'e4', 'dxe4', 'Bxe4', 'Ne7'],
    fen: 'rnbqkbnr/ppp1pppp/8/3p4/3P1B2/8/PPP1PPPP/RN1QKBNR b KQkq - 1 2',
    description: 'A solid, easy-to-learn system where White develops the dark-squared bishop before playing e3. Great for beginners who want a reliable setup.',
    difficulty: 'beginner',
    category: 'd4',
    popularity: 75,
    winRate: { white: 38, draw: 33, black: 29 },
    keyIdeas: [
      'Develop bishop to f4 before playing e3',
      'Build a solid pyramid structure',
      'Flexible - works against most Black setups',
      'Simple plans with minimal theory required'
    ],
    moveAnnotations: [
      'Opens with the queen pawn',
      'Black mirrors the center',
      'The London! Bishop before e3 is the key move order',
      'Natural development',
      'Supports d4 and completes the pawn structure',
      'Black challenges the center',
      'Reinforces d4',
      'Develops with pressure on d4',
      'Develops without blocking the c-pawn',
      'Solid structure for Black',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Main Line', moves: ['d4', 'd5', 'Bf4', 'Nf6', 'e3', 'c5', 'c3', 'Nc6', 'Nd2', 'e6', 'Ngf3', 'Bd6', 'Bg3', 'O-O', 'Bd3', 'b6', 'Qe2', 'Bb7'], description: 'The standard setup with a solid center - plans h3, Ne5' },
      { name: 'Jobava London', moves: ['d4', 'd5', 'Bf4', 'Nf6', 'Nc3', 'e6', 'e3', 'c5', 'Nb5', 'Na6', 'c3', 'Bd6', 'Bxd6', 'Qxd6', 'Qa4', 'O-O'], description: 'More aggressive with Nc3 instead of e3 - leads to sharper play' },
      { name: 'London vs King\'s Indian', moves: ['d4', 'Nf6', 'Bf4', 'g6', 'e3', 'Bg7', 'Nf3', 'O-O', 'Be2', 'd6', 'O-O', 'Nbd7', 'h3', 'Qe8', 'c3', 'e5', 'Bh2', 'Nh5'], description: 'Handling Black\'s fianchetto setup with a solid structure' },
    ]
  },
  {
    id: 'caro-kann',
    name: 'Caro-Kann Defense',
    eco: 'B10',
    moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Bf5', 'Ng3', 'Bg6', 'h4', 'h6', 'Nf3', 'Nd7', 'h5', 'Bh7', 'Bd3', 'Bxd3', 'Qxd3', 'e6', 'Bf4', 'Ngf6', 'O-O-O', 'Be7', 'Kb1', 'O-O', 'Ne5', 'c5', 'Nxd7', 'Qxd7', 'dxc5', 'Bxc5', 'Qe2'],
    fen: 'rnbqkbnr/pp1ppppp/2p5/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
    description: 'A very solid defense that avoids the typical problems of the French Defense. Black keeps the light-squared bishop active.',
    difficulty: 'intermediate',
    category: 'e4',
    popularity: 76,
    winRate: { white: 36, draw: 33, black: 31 },
    keyIdeas: [
      'Solid pawn structure with d5 support',
      'Light-squared bishop remains active',
      'Less cramped than the French Defense',
      'Reliable at all levels of play'
    ],
    moveAnnotations: [
      'Claims the center',
      'The Caro-Kann — prepares d5 while keeping the bishop diagonal open',
      'Full center',
      'Challenges immediately',
      'Defends e4',
      'Exchanges to relieve tension',
      'Recaptures centrally',
      'The key idea! Develops the bishop before e6',
      'Chases the bishop',
      'Retreats but stays active',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Classical (Bf5)', moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Bf5', 'Ng3', 'Bg6', 'h4', 'h6', 'Nf3', 'Nd7', 'h5', 'Bh7', 'Bd3', 'Bxd3', 'Qxd3', 'e6'], description: 'Main line where Black develops the bishop to f5 before e6' },
      { name: 'Advance', moves: ['e4', 'c6', 'd4', 'd5', 'e5', 'Bf5', 'Nf3', 'e6', 'Be2', 'c5', 'Be3', 'Nd7', 'O-O', 'Ne7', 'c3', 'Nc6'], description: 'White grabs space with e5, Black counterattacks the chain' },
      { name: 'Exchange', moves: ['e4', 'c6', 'd4', 'd5', 'exd5', 'cxd5', 'Bd3', 'Nc6', 'c3', 'Nf6', 'Bf4', 'Bg4', 'Qb3', 'Qd7'], description: 'Symmetrical but White has a slight edge with more active pieces' },
      { name: 'Fantasy (f3)', moves: ['e4', 'c6', 'd4', 'd5', 'f3', 'dxe4', 'fxe4', 'e5', 'Nf3', 'Bg4', 'Bc4', 'Nd7', 'O-O', 'Ngf6'], description: 'Aggressive and unorthodox - White builds a big center' },
      { name: 'Panov-Botvinnik Attack', moves: ['e4', 'c6', 'd4', 'd5', 'exd5', 'cxd5', 'c4', 'Nf6', 'Nc3', 'e6', 'Nf3', 'Be7', 'cxd5', 'Nxd5', 'Bd3'], description: 'Creates an IQP position with attacking chances' },
    ]
  },
  {
    id: 'english-opening',
    name: 'English Opening',
    eco: 'A10',
    moves: ['c4', 'e5', 'Nc3', 'Nf6', 'Nf3', 'Nc6', 'g3', 'Bb4', 'Bg2', 'O-O', 'O-O', 'e4', 'Ng5', 'Bxc3', 'bxc3', 'Re8', 'd3', 'exd3', 'Qxd3', 'd6', 'Rb1', 'h6', 'Nf3', 'Bg4', 'h3', 'Bh5', 'g4', 'Bg6', 'Nh4', 'Ne5', 'Qe3'],
    fen: 'rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq c3 0 1',
    description: 'A flexible flank opening that can transpose into many other openings. Named after Howard Staunton who employed it in 1843.',
    difficulty: 'intermediate',
    category: 'other',
    popularity: 70,
    winRate: { white: 37, draw: 34, black: 29 },
    keyIdeas: [
      'Control d5 from the flank',
      'Flexible - can transpose into many systems',
      'Often leads to strategic positions',
      'Good for players who like variety'
    ],
    moveAnnotations: [
      'The English! Controls d5 from the flank',
      'Black grabs the center',
      'Develops toward d5',
      'Develops and contests e4',
      'Attacks e5',
      'Defends e5',
      'Prepares the fianchetto',
      'Pins the knight',
      'Powerful fianchettoed bishop',
      'Castles early for safety',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Symmetrical', moves: ['c4', 'c5', 'Nc3', 'Nc6', 'g3', 'g6', 'Bg2', 'Bg7', 'Nf3', 'Nf6', 'O-O', 'O-O', 'd3', 'd6', 'a3', 'a6', 'Rb1', 'Rb8'], description: 'Black mirrors White\'s approach leading to complex strategic battles' },
      { name: 'Reversed Sicilian', moves: ['c4', 'e5', 'Nc3', 'Nf6', 'Nf3', 'Nc6', 'd3', 'Bb4', 'g3', 'O-O', 'Bg2', 'Re8', 'O-O', 'd6', 'Nd5', 'Bc5'], description: 'White plays a reversed Sicilian with an extra tempo' },
      { name: 'Four Knights', moves: ['c4', 'e5', 'Nc3', 'Nf6', 'Nf3', 'Nc6', 'g3', 'd5', 'cxd5', 'Nxd5', 'Bg2', 'Nb6', 'O-O', 'Be7', 'd3', 'O-O'], description: 'Solid setup often reaching Sicilian-type positions' },
    ]
  },
  {
    id: 'scotch-game',
    name: 'Scotch Game',
    eco: 'C45',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Nf6', 'Nxc6', 'bxc6', 'e5', 'Qe7', 'Qe2', 'Nd5', 'c4', 'Ba6', 'b3', 'g6', 'Ba3', 'Qe6', 'Nd2', 'Bg7', 'O-O-O', 'O-O-O', 'Re1', 'Rhe8', 'Nf3', 'Nb4', 'Bb2', 'c5', 'Nd4', 'Qd5'],
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq d3 0 3',
    description: 'An aggressive opening where White immediately challenges the center. Garry Kasparov revived this opening in the 1990s.',
    difficulty: 'beginner',
    category: 'e4',
    popularity: 72,
    winRate: { white: 39, draw: 29, black: 32 },
    keyIdeas: [
      'Immediate central confrontation',
      'Open lines for rapid development',
      'Active piece play for both sides',
      'Leads to dynamic middlegames'
    ],
    moveAnnotations: [
      'Center control',
      'Symmetrical center',
      'Develops and attacks e5',
      'Defends e5',
      'The Scotch! Immediately opens the center',
      'Black must capture',
      'Recaptures with the knight centrally',
      'Counter-attacks e4',
      'Exchanges to damage Black\'s pawn structure',
      'Forced recapture, doubled c-pawns',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Classical', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Bc5', 'Be3', 'Qf6', 'c3', 'Nge7', 'Bc4', 'Ne5', 'Be2', 'Qg6', 'O-O', 'd6'], description: 'Black develops actively against the knight with Bc5' },
      { name: 'Scotch Gambit', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Bc4', 'Nf6', 'e5', 'd5', 'Bb5', 'Ne4', 'Nxd4', 'Bd7', 'Bxc6', 'bxc6', 'O-O'], description: 'White sacrifices a pawn for rapid development and attacking chances' },
      { name: 'Mieses Variation', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Nf6', 'Nxc6', 'bxc6', 'e5', 'Qe7', 'Qe2', 'Nd5', 'c4', 'Ba6', 'Nd2'], description: 'Main line exchange on c6 leading to endgame-type positions' },
    ]
  },
  {
    id: 'nimzo-indian',
    name: 'Nimzo-Indian Defense',
    eco: 'E20',
    moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'Qc2', 'O-O', 'a3', 'Bxc3+', 'Qxc3', 'd5', 'Nf3', 'dxc4', 'Qxc4', 'b6', 'Bg5', 'Ba6', 'Qa4', 'h6', 'Bh4', 'c5', 'dxc5', 'bxc5', 'Rd1', 'Qb6', 'e3', 'Nbd7', 'Be2', 'Rac8'],
    fen: 'rnbqkb1r/pppp1ppp/4pn2/8/1bPP4/2N5/PP2PPPP/R1BQKBNR w KQkq - 2 4',
    description: 'One of the most respected defenses against 1.d4. Black pins the knight and is ready to double White\'s pawns.',
    difficulty: 'advanced',
    category: 'd4',
    popularity: 85,
    winRate: { white: 36, draw: 34, black: 30 },
    keyIdeas: [
      'Pin the c3 knight with Bb4',
      'Double White\'s pawns after Bxc3',
      'Control e4 square',
      'Flexible pawn structure choices'
    ],
    moveAnnotations: [
      'Opens with the queen pawn',
      'Flexible — waits to see White\'s setup',
      'Expands the center',
      'Prepares the Nimzo pin',
      'Develops naturally',
      'The Nimzo-Indian! Pins the knight to the king',
      'Prevents doubled pawns after Bxc3',
      'Castles first',
      'Forces the bishop to make a decision',
      'Captures, doubling White\'s pawns',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Classical', moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'Qc2', 'O-O', 'a3', 'Bxc3+', 'Qxc3', 'b6', 'Bg5', 'Bb7', 'e3', 'd6', 'Nf3', 'Nbd7'], description: 'Main line with Qc2 preventing doubled pawns' },
      { name: 'Samisch', moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'a3', 'Bxc3+', 'bxc3', 'c5', 'e3', 'Nc6', 'Bd3', 'O-O', 'Ne2', 'b6', 'e4', 'Ne8'], description: 'White accepts doubled pawns for the bishop pair' },
      { name: 'Rubinstein', moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'e3', 'O-O', 'Bd3', 'd5', 'Nf3', 'c5', 'O-O', 'dxc4', 'Bxc4', 'Nbd7'], description: 'Solid setup with e3 and normal development' },
    ]
  },
  {
    id: 'grunfeld-defense',
    name: 'Grünfeld Defense',
    eco: 'D80',
    moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'cxd5', 'Nxd5', 'e4', 'Nxc3', 'bxc3', 'Bg7', 'Nf3', 'c5', 'Be3', 'Qa5', 'Qd2', 'O-O', 'Rc1', 'cxd4', 'cxd4', 'Qxd2+', 'Kxd2', 'Rd8', 'Ke1', 'Nc6', 'd5', 'Ne5', 'Nxe5', 'Bxe5', 'f3', 'Bd7'],
    fen: 'rnbqkb1r/ppp1pp1p/5np1/3p4/2PP4/2N5/PP2PPPP/R1BQKBNR w KQkq - 0 4',
    description: 'A hypermodern defense where Black allows White a big center, then attacks it with pieces and the fianchettoed bishop.',
    difficulty: 'advanced',
    category: 'd4',
    popularity: 78,
    winRate: { white: 38, draw: 30, black: 32 },
    keyIdeas: [
      'Allow White a large pawn center',
      'Attack the center with Bg7 and c5',
      'Dynamic piece play',
      'Sharp theoretical battles'
    ],
    moveAnnotations: [
      'Central pawn opening',
      'Flexible knight development',
      'Expands the center',
      'Prepares the fianchetto',
      'Develops',
      'The Grünfeld! Strikes the center immediately',
      'Captures in the center',
      'Recaptures with the knight',
      'Kicks the knight, building a massive center',
      'Exchanges before retreating',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Exchange', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'cxd5', 'Nxd5', 'e4', 'Nxc3', 'bxc3', 'Bg7', 'Nf3', 'c5', 'Rb1', 'O-O', 'Be2', 'cxd4', 'cxd4', 'Qa5+', 'Bd2', 'Qxa2'], description: 'Main line with White\'s massive center under constant pressure' },
      { name: 'Russian System', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'Nf3', 'Bg7', 'Qb3', 'dxc4', 'Qxc4', 'O-O', 'e4', 'a6', 'Be2', 'b5', 'Qb3', 'c5'], description: 'Early Qb3 prevents Black from easily winning back the pawn' },
    ]
  },
  {
    id: 'dutch-defense',
    name: 'Dutch Defense',
    eco: 'A80',
    moves: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'e6', 'Nf3', 'Be7', 'O-O', 'O-O', 'c4', 'd6', 'Nc3', 'Qe8', 'Qc2', 'Qh5', 'b3', 'Nc6', 'Ba3', 'a5', 'Nb5', 'Bd7', 'Nxd6', 'cxd6', 'Bxd6', 'Bxd6', 'Qxf5', 'Ne4', 'Qh3', 'Qxh3', 'Bxh3', 'Nxd4', 'Nxd4'],
    fen: 'rnbqkbnr/ppppp1pp/8/5p2/3P4/8/PPP1PPPP/RNBQKBNR w KQkq f6 0 2',
    description: 'An aggressive defense where Black stakes a claim on the kingside with f5. It leads to unbalanced positions.',
    difficulty: 'intermediate',
    category: 'd4',
    popularity: 65,
    winRate: { white: 40, draw: 28, black: 32 },
    keyIdeas: [
      'Control e4 with f5',
      'Kingside attacking chances',
      'Stonewall or Leningrad structures',
      'Dynamic imbalanced positions'
    ],
    moveAnnotations: [
      'Center control',
      'The Dutch! Aggressive — controls e4 from the wing',
      'Prepares the fianchetto',
      'Develops naturally',
      'Fianchettoes the bishop',
      'Solid structure',
      'Develops',
      'Prepares castling',
      'Castles',
      'Both sides castled',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Stonewall', moves: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'e6', 'Nf3', 'd5', 'O-O', 'c6', 'c4', 'Bd6', 'b3', 'Qe7', 'Bb2', 'O-O', 'Qc1', 'b6'], description: 'Solid pawn structure with d5-e6-f5, good for attacking' },
      { name: 'Leningrad', moves: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'g6', 'Nf3', 'Bg7', 'O-O', 'O-O', 'c4', 'd6', 'Nc3', 'Nc6', 'd5', 'Ne5', 'Nxe5', 'dxe5'], description: 'Fianchetto setup resembling King\'s Indian with attacking chances' },
    ]
  },
  {
    id: 'vienna-game',
    name: 'Vienna Game',
    eco: 'C25',
    moves: ['e4', 'e5', 'Nc3', 'Nf6', 'f4', 'd5', 'fxe5', 'Nxe4', 'Nf3', 'Bg4', 'Qe2', 'Nc6', 'd3', 'Nxc3', 'bxc3', 'Be7', 'Be3', 'O-O', 'O-O-O', 'Qd7', 'Kb1', 'Rab8', 'h3', 'Bh5', 'g4', 'Bg6', 'Bg2', 'Rfe8', 'Rhe1', 'd4', 'Bf2'],
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/2N5/PPPP1PPP/R1BQKBNR b KQkq - 1 2',
    description: 'A romantic opening where White prepares f4 to attack the center. It can lead to sharp tactical positions.',
    difficulty: 'intermediate',
    category: 'e4',
    popularity: 68,
    winRate: { white: 37, draw: 30, black: 33 },
    keyIdeas: [
      'Prepare f4 pawn push',
      'Attack the e5 pawn',
      'Rapid piece activity',
      'Can transpose to King\'s Gambit'
    ],
    moveAnnotations: [
      'Center control',
      'Symmetrical',
      'The Vienna! Develops knight before f4',
      'Attacks e4',
      'The gambit thrust — aims to break open the center',
      'Black strikes back in the center',
      'Captures the pawn',
      'Black wins the e4 pawn — temporarily material even',
      'Develops with tempo',
      'Pins the knight to the queen',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Vienna Gambit', moves: ['e4', 'e5', 'Nc3', 'Nf6', 'f4', 'd5', 'fxe5', 'Nxe4', 'Qf3', 'Nc6', 'Bb5', 'Nxc3', 'dxc3', 'Qh4+', 'g3', 'Qe4+'], description: 'Aggressive pawn sacrifice for attacking chances' },
      { name: 'Frankenstein-Dracula', moves: ['e4', 'e5', 'Nc3', 'Nf6', 'Bc4', 'Nxe4', 'Qh5', 'Nd6', 'Bb3', 'Nc6', 'Nb5', 'g6', 'Qf3', 'f5', 'Qd5', 'Qe7'], description: 'Wild tactical variation with early Qh5' },
    ]
  },
  {
    id: 'pirc-defense',
    name: 'Pirc Defense',
    eco: 'B07',
    moves: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'f4', 'Bg7', 'Nf3', 'O-O', 'Bd3', 'Nc6', 'O-O', 'e5', 'fxe5', 'dxe5', 'd5', 'Ne7', 'Be3', 'Nd7', 'a4', 'f5', 'exf5', 'Nxf5', 'Bf2', 'Nf6', 'Qe1', 'Nd4', 'Nxd4', 'exd4', 'Ne2'],
    fen: 'rnbqkbnr/ppp1pppp/3p4/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
    description: 'A flexible hypermodern defense where Black develops the kingside bishop to g7 and attacks the center from afar.',
    difficulty: 'intermediate',
    category: 'e4',
    popularity: 70,
    winRate: { white: 38, draw: 29, black: 33 },
    keyIdeas: [
      'Fianchetto the dark-squared bishop',
      'Flexible pawn structure',
      'Counter-attack the center',
      'Can transpose to many systems'
    ],
    moveAnnotations: [
      'Central space',
      'The Pirc — allows White a big center to attack later',
      'Full center',
      'Nibbles at e4',
      'Supports e4',
      'Prepares the fianchetto',
      'The Austrian Attack — aggressive!',
      'Fianchettoed bishop aims at d4',
      'Completes development',
      'Castles, preparing counterplay',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
    ],
    variations: [
      { name: 'Austrian Attack', moves: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'f4', 'Bg7', 'Nf3', 'c5', 'Bb5+', 'Bd7', 'e5', 'Ng4', 'e6', 'fxe6', 'Ng5'], description: 'Aggressive f4 system with attacking intentions' },
      { name: 'Classical', moves: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'Nf3', 'Bg7', 'Be2', 'O-O', 'O-O', 'c6', 'a4', 'Nbd7', 'h3', 'e5'], description: 'Solid development allowing Black counterplay with ...e5' },
    ]
  },
  {
    id: 'scandinavian-defense',
    name: 'Scandinavian Defense',
    eco: 'B01',
    moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5', 'd4', 'Nf6', 'Nf3', 'Bf5', 'Bc4', 'e6'],
    fen: 'rnbqkbnr/ppp1pppp/8/3p4/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
    description: 'An aggressive defense where Black immediately challenges White\'s e4 pawn. The early queen development is compensated by active piece play.',
    difficulty: 'beginner',
    category: 'e4',
    popularity: 74,
    winRate: { white: 39, draw: 28, black: 33 },
    keyIdeas: [
      'Immediately challenge the e4 pawn',
      'Develop the queen early but actively',
      'Solid pawn structure for Black',
      'Quick development of minor pieces'
    ],
    variations: [
      { name: 'Center Counter', moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5', 'd4', 'Nf6', 'Nf3', 'c6', 'Bc4', 'Bf5', 'Bd2', 'e6', 'Nd5', 'Qd8', 'Nxf6+', 'gxf6'], description: 'Classical line with queen retreat to a5 and solid pawn structure' },
      { name: 'Modern Scandinavian', moves: ['e4', 'd5', 'exd5', 'Nf6', 'd4', 'Nxd5', 'Nf3', 'g6', 'Be2', 'Bg7', 'O-O', 'O-O', 'c4', 'Nb6', 'Nc3', 'Nc6'], description: 'Black recaptures with the knight instead of the queen for flexible development' },
    ]
  },
  {
    id: 'catalan-opening',
    name: 'Catalan Opening',
    eco: 'E00',
    moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2', 'Be7', 'Nf3', 'O-O', 'O-O', 'dxc4'],
    fen: 'rnbqkb1r/pppp1ppp/4pn2/8/2PP4/6P1/PP2PP1P/RNBQKBNR b KQkq - 0 3',
    description: 'A sophisticated opening combining Queen\'s Gambit pawn structure with a kingside fianchetto. The Bg2 exerts long-term pressure on the queenside.',
    difficulty: 'advanced',
    category: 'd4',
    popularity: 78,
    winRate: { white: 40, draw: 33, black: 27 },
    keyIdeas: [
      'Fianchetto the light-squared bishop to g2',
      'Long-term pressure on the long diagonal',
      'Combine positional and dynamic play',
      'Regain the c4 pawn with interest'
    ],
    variations: [
      { name: 'Open Catalan', moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2', 'dxc4', 'Nf3', 'Be7', 'O-O', 'O-O', 'Qc2', 'a6', 'a4', 'Bd7'], description: 'Black takes on c4 and tries to hold the extra pawn' },
      { name: 'Closed Catalan', moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2', 'Be7', 'Nf3', 'O-O', 'O-O', 'Nbd7', 'Qc2', 'c6', 'Nbd2', 'b6'], description: 'Black maintains the pawn tension and develops solidly' },
    ]
  },
  {
    id: 'alekhine-defense',
    name: 'Alekhine Defense',
    eco: 'B02',
    moves: ['e4', 'Nf6', 'e5', 'Nd5', 'd4', 'd6', 'Nf3', 'Bg4', 'Be2', 'e6', 'O-O', 'Be7'],
    fen: 'rnbqkb1r/pppppppp/5n2/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 1 2',
    description: 'A provocative defense where Black invites White to advance pawns in the center, then seeks to undermine and attack the overextended pawn chain.',
    difficulty: 'intermediate',
    category: 'e4',
    popularity: 62,
    winRate: { white: 40, draw: 28, black: 32 },
    keyIdeas: [
      'Provoke White\'s pawns forward',
      'Attack the overextended pawn center',
      'Knight maneuvers to pressure weak pawns',
      'Counterattack rather than defend passively'
    ],
    variations: [
      { name: 'Four Pawns Attack', moves: ['e4', 'Nf6', 'e5', 'Nd5', 'd4', 'd6', 'c4', 'Nb6', 'f4', 'dxe5', 'fxe5', 'Nc6', 'Be3', 'Bf5', 'Nc3', 'e6'], description: 'White pushes four pawns aggressively but risks overextension' },
      { name: 'Exchange Variation', moves: ['e4', 'Nf6', 'e5', 'Nd5', 'd4', 'd6', 'c4', 'Nb6', 'exd6', 'cxd6', 'Nc3', 'g6', 'Be3', 'Bg7', 'Rc1', 'O-O'], description: 'White exchanges the e-pawn for a solid but less ambitious position' },
    ]
  },
  {
    id: 'benoni-defense',
    name: 'Benoni Defense',
    eco: 'A60',
    moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6', 'e4', 'g6', 'Nf3', 'Bg7'],
    fen: 'rnbqkb1r/pp1ppppp/5n2/2pP4/2P5/8/PP2PPPP/RNBQKBNR b KQkq - 0 3',
    description: 'A dynamic defense where Black creates an asymmetric pawn structure. Black gets kingside play and a queenside pawn majority, while White has a central space advantage.',
    difficulty: 'advanced',
    category: 'd4',
    popularity: 66,
    winRate: { white: 41, draw: 27, black: 32 },
    keyIdeas: [
      'Create asymmetric pawn structure',
      'Fianchetto the dark-squared bishop',
      'Advance the queenside pawn majority',
      'Active piece play to compensate for space disadvantage'
    ],
    variations: [
      { name: 'Classical Benoni', moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6', 'e4', 'g6', 'Nf3', 'Bg7', 'Be2', 'O-O', 'O-O', 'Re8'], description: 'The main line with natural development and kingside fianchetto' },
      { name: 'Taimanov Variation', moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6', 'e4', 'g6', 'f4', 'Bg7', 'Bb5+', 'Nfd7', 'a4', 'O-O'], description: 'White plays f4 for an aggressive setup with a strong pawn center' },
    ]
  },
  {
    id: 'philidor-defense',
    name: 'Philidor Defense',
    eco: 'C41',
    moves: ['e4', 'e5', 'Nf3', 'd6', 'd4', 'Nf6', 'Nc3', 'Be7', 'Bc4', 'O-O', 'O-O', 'c6'],
    fen: 'rnbqkbnr/ppp2ppp/3p4/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 3',
    description: 'A solid but passive defense where Black supports the e5 pawn with d6. Favored by Philidor who declared "pawns are the soul of chess".',
    difficulty: 'beginner',
    category: 'e4',
    popularity: 68,
    winRate: { white: 40, draw: 30, black: 30 },
    keyIdeas: [
      'Solid pawn structure supporting e5',
      'Develop pieces behind the pawn chain',
      'Prepare kingside castling quickly',
      'Counterattack in the center when ready'
    ],
    variations: [
      { name: 'Hanham Variation', moves: ['e4', 'e5', 'Nf3', 'd6', 'd4', 'Nd7', 'Bc4', 'c6', 'O-O', 'Be7', 'a4', 'Ngf6', 'Re1', 'O-O'], description: 'A solid setup with Nd7 keeping options flexible for the other knight' },
      { name: 'Exchange Variation', moves: ['e4', 'e5', 'Nf3', 'd6', 'd4', 'exd4', 'Nxd4', 'Nf6', 'Nc3', 'Be7', 'Be2', 'O-O', 'O-O', 'c5', 'Nf3', 'Nc6'], description: 'The exchange leads to open positions with active piece play for both sides' },
    ]
  },
]

export const PUZZLES: Puzzle[] = [
  // === EASY PUZZLES (Rating 400-600) ===
  {
    id: 'p1',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    moves: ['Qxf7#'],
    rating: 400,
    themes: ['mate', 'scholarsMate'],
    title: "Scholar's Mate",
    description: 'Find the checkmate in one move!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p2',
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/6P1/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 2',
    moves: ['Qh4#'],
    rating: 400,
    themes: ['mate', 'foolsMate'],
    title: "Fool's Mate",
    description: 'White has weakened the kingside terribly!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p3',
    fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    moves: ['Re8#'],
    rating: 450,
    themes: ['mate', 'backRank'],
    title: 'Back Rank Mate',
    description: 'The king is trapped. Find checkmate!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p4',
    fen: '8/8/8/8/8/1k6/8/1K1Q4 w - - 0 1',
    moves: ['Qd3#'],
    rating: 450,
    themes: ['mate', 'queenMate'],
    title: 'Queen Checkmate',
    description: 'Deliver checkmate with queen support.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p5',
    fen: '8/8/8/8/8/1k6/R7/1K6 w - - 0 1',
    moves: ['Ra3#'],
    rating: 450,
    themes: ['mate', 'rookMate'],
    title: 'Rook Checkmate',
    description: 'Deliver checkmate with rook support.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p6',
    fen: '6k1/5ppp/8/8/8/8/5PPP/R3R1K1 w - - 0 1',
    moves: ['Re8#'],
    rating: 500,
    themes: ['mate', 'backRank'],
    title: 'Double Rook Power',
    description: 'Deliver the back rank mate!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p7',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    moves: ['Ng5'],
    rating: 550,
    themes: ['attack', 'threat'],
    title: 'Attack f7',
    description: 'Threaten the weak f7 pawn.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p8',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    moves: ['Bc4'],
    rating: 550,
    themes: ['development', 'opening'],
    title: 'Italian Opening',
    description: 'Find the best developing move.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p9',
    fen: '6rk/6pp/8/6N1/8/8/8/6K1 w - - 0 1',
    moves: ['Nf7#'],
    rating: 500,
    themes: ['mate', 'smotheredMate'],
    title: 'Smothered Mate',
    description: 'Deliver checkmate with the knight!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p10',
    fen: '5rk1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1',
    moves: ['Qd8'],
    rating: 550,
    themes: ['tactic', 'backRank'],
    title: 'Queen Threat',
    description: 'Force an exchange with back rank threat.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p11',
    fen: 'rnbqkbnr/ppp2ppp/8/3pp3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq d6 0 3',
    moves: ['Nxe5'],
    rating: 600,
    themes: ['tactic', 'capture'],
    title: 'Free Pawn',
    description: 'Capture the undefended pawn.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p12',
    fen: 'r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3',
    moves: ['a6'],
    rating: 600,
    themes: ['defense', 'kickBishop'],
    title: 'Kick the Bishop',
    description: 'Challenge Whites strong bishop.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p13',
    fen: '4k3/8/8/8/8/3R4/8/4K3 w - - 0 1',
    moves: ['Rd8+'],
    rating: 500,
    themes: ['tactic', 'check'],
    title: 'Rook Check',
    description: 'Give check to improve position.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p14',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    moves: ['Ng5', 'd5', 'exd5'],
    rating: 600,
    themes: ['attack', 'opening'],
    title: 'Fried Liver Setup',
    description: 'Begin the famous attack!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p15',
    fen: 'rnbqkb1r/pppppppp/5n2/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 1 2',
    moves: ['e5'],
    rating: 550,
    themes: ['opening', 'space'],
    title: 'Gain Space',
    description: 'Push the pawn to attack.',
    difficulty: 'easy',
    xpReward: 10,
  },
  // === MEDIUM PUZZLES (Rating 700-950) ===
  {
    id: 'p16',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 5',
    moves: ['Bg5', 'h6', 'Bh4'],
    rating: 750,
    themes: ['pin', 'pressure'],
    title: 'Pin the Knight',
    description: 'Use a pin to apply pressure.',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p17',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 5',
    moves: ['O-O', 'O-O', 'Nc3'],
    rating: 750,
    themes: ['development', 'castling'],
    title: 'Castle and Develop',
    description: 'Get king to safety.',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p18',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 4 4',
    moves: ['Nxe5', 'Nxe5', 'd4'],
    rating: 800,
    themes: ['tactic', 'fork'],
    title: 'Fork Trick',
    description: 'Win a pawn tactically.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p19',
    fen: 'rnbqkb1r/pppp1ppp/5n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    moves: ['d3', 'd6', 'Bg5'],
    rating: 800,
    themes: ['opening', 'development'],
    title: 'Italian Game',
    description: 'Build up pressure.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p20',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 4 4',
    moves: ['Qf7#'],
    rating: 700,
    themes: ['mate', 'tactics'],
    title: 'Quick Strike',
    description: 'Find the instant checkmate!',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p21',
    fen: 'rnbqkb1r/ppp2ppp/3p1n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    moves: ['d4', 'exd4', 'Nxd4'],
    rating: 850,
    themes: ['center', 'pawnBreak'],
    title: 'Central Break',
    description: 'Open up the center.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p22',
    fen: 'rnbqkb1r/ppp2ppp/3p1n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    moves: ['Nc3', 'Be7', 'O-O'],
    rating: 800,
    themes: ['development', 'opening'],
    title: 'Complete Development',
    description: 'Finish development first.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p23',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R w KQkq - 0 4',
    moves: ['dxe5', 'Nxe4', 'Qd5'],
    rating: 900,
    themes: ['tactic', 'discovered'],
    title: 'Discovered Attack',
    description: 'Open lines for an attack.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p24',
    fen: 'r1bqkb1r/ppp2ppp/2np1n2/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 5',
    moves: ['d3', 'Be7', 'O-O'],
    rating: 850,
    themes: ['strategy', 'development'],
    title: 'Solid Setup',
    description: 'Set up solidly.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p25',
    fen: 'r4rk1/ppp2ppp/2n5/3N4/3q4/8/PPP2PPP/R2Q1RK1 w - - 0 12',
    moves: ['Nxc7', 'Qxd1', 'Rfxd1'],
    rating: 950,
    themes: ['tactic', 'combination'],
    title: 'Win Material',
    description: 'Find the winning sequence.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p26',
    fen: '6k1/8/8/8/8/8/6Q1/6K1 w - - 0 1',
    moves: ['Qg7#'],
    rating: 700,
    themes: ['mate', 'pattern'],
    title: 'Queen Mate Pattern',
    description: 'Find the simple checkmate.',
    difficulty: 'medium',
    xpReward: 15,
  },
  {
    id: 'p27',
    fen: '7k/8/6B1/5B2/8/8/8/7K w - - 0 1',
    moves: ['Be4'],
    rating: 850,
    themes: ['endgame', 'bishops'],
    title: 'Bishop Restriction',
    description: 'Restrict the kings movement.',
    difficulty: 'medium',
    xpReward: 20,
  },
  {
    id: 'p28',
    fen: '8/8/4k3/8/8/8/8/4RK2 w - - 0 1',
    moves: ['Re4'],
    rating: 900,
    themes: ['endgame', 'rook'],
    title: 'Rook Cutoff',
    description: 'Cut off the king.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p29',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2B1n3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    moves: ['Bxf7+', 'Ke7', 'd3'],
    rating: 950,
    themes: ['tactic', 'sacrifice'],
    title: 'Win Material',
    description: 'Win material with a sacrifice.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p30',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 6 5',
    moves: ['d3', 'd6', 'c3'],
    rating: 900,
    themes: ['opening', 'italian'],
    title: 'Italian Classical',
    description: 'Build a solid position.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p31',
    fen: 'rnbqkb1r/pp2pppp/2p2n2/3p4/2PP4/2N5/PP2PPPP/R1BQKBNR w KQkq - 0 4',
    moves: ['e3', 'e6', 'Bd3'],
    rating: 950,
    themes: ['opening', 'slav'],
    title: 'Slav Defense',
    description: 'Play the Slav Defense setup.',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p32',
    fen: 'r1bqkb1r/pp1npppp/2p2n2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 2 5',
    moves: ['e3', 'e6', 'Bd3'],
    rating: 900,
    themes: ['opening', 'qgd'],
    title: 'QGD Setup',
    description: 'Set up the Queens Gambit Declined.',
    difficulty: 'medium',
    xpReward: 25,
  },
  // === HARD PUZZLES (Rating 1100-1400) ===
  {
    id: 'p33',
    fen: 'r1b1k2r/ppppqppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 4 5',
    moves: ['Ng5', 'O-O', 'Nxh7'],
    rating: 1150,
    themes: ['attack', 'sacrifice'],
    title: 'Knight Attack',
    description: 'Launch a kingside attack.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p34',
    fen: 'r1bq1rk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQ1RK1 w - - 0 7',
    moves: ['h3', 'h6', 'Be3'],
    rating: 1200,
    themes: ['strategy', 'prophylaxis'],
    title: 'Prophylaxis',
    description: 'Prevent threats while improving.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p35',
    fen: 'r1b2rk1/ppp2ppp/2n2n2/3qp3/3P4/2N2N2/PPP2PPP/R1BQ1RK1 w - - 0 9',
    moves: ['dxe5', 'Nxe5', 'Nxe5'],
    rating: 1250,
    themes: ['tactic', 'exchange'],
    title: 'Exchange and Win',
    description: 'Win material precisely.',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p36',
    fen: 'r1bq1rk1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQR1K1 w - - 0 8',
    moves: ['Nd5', 'Nxd5', 'exd5'],
    rating: 1300,
    themes: ['strategy', 'outpost'],
    title: 'Knight Jump',
    description: 'Control key squares.',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p37',
    fen: 'r1bq1rk1/ppp2ppp/2n2n2/3p4/1bPP4/2N1PN2/PP3PPP/R1BQKB1R w KQ - 0 6',
    moves: ['a3', 'Bxc3+', 'bxc3'],
    rating: 1200,
    themes: ['strategy', 'bishopPair'],
    title: 'Bishop Pair',
    description: 'Win the bishop pair.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p38',
    fen: 'r1bq1rk1/pp1n1ppp/2pbpn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 8',
    moves: ['b4', 'a6', 'a4'],
    rating: 1350,
    themes: ['strategy', 'minorityAttack'],
    title: 'Minority Attack',
    description: 'Attack the queenside.',
    difficulty: 'hard',
    xpReward: 45,
  },
  {
    id: 'p39',
    fen: 'r1bq1rk1/pppn1ppp/4pn2/3p4/1bPP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 2 7',
    moves: ['cxd5', 'exd5', 'Qc2'],
    rating: 1300,
    themes: ['strategy', 'openLines'],
    title: 'Open Lines',
    description: 'Open lines for pieces.',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p40',
    fen: 'rnbqkb1r/pppppp1p/5np1/8/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3',
    moves: ['Nc3', 'Bg7', 'e4'],
    rating: 1200,
    themes: ['opening', 'kingsIndian'],
    title: 'Kings Indian',
    description: 'Face the Kings Indian Defense.',
    difficulty: 'hard',
    xpReward: 35,
  },
  {
    id: 'p41',
    fen: 'r2q1rk1/pp2ppbp/2np1np1/8/3NP3/2N1B3/PPPQBPPP/R3K2R w KQ - 0 9',
    moves: ['O-O-O', 'Qa5', 'f3'],
    rating: 1400,
    themes: ['attack', 'sicilian'],
    title: 'Sicilian Dragon',
    description: 'Set up your attack.',
    difficulty: 'hard',
    xpReward: 45,
  },
  // === EXPERT PUZZLES (Rating 1500-1800) ===
  {
    id: 'p42',
    fen: '2r3k1/5ppp/8/8/8/8/5PPP/2R3K1 w - - 0 1',
    moves: ['Rc4', 'Kf8', 'Ra4'],
    rating: 1500,
    themes: ['endgame', 'simplification'],
    title: 'Rook Endgame',
    description: 'Improve your rook position.',
    difficulty: 'expert',
    xpReward: 50,
  },
  {
    id: 'p43',
    fen: '8/8/8/8/8/5k2/5P2/5K2 w - - 0 1',
    moves: ['Ke1', 'Ke4', 'Ke2'],
    rating: 1550,
    themes: ['endgame', 'pawnEndgame'],
    title: 'Pawn Endgame',
    description: 'Navigate correctly.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p44',
    fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/3NP3/2N1B3/PPPQBPPP/R3K2R w KQ - 0 9',
    moves: ['O-O-O', 'a6', 'f3'],
    rating: 1600,
    themes: ['attack', 'oppositeCastling'],
    title: 'Opposite Castling',
    description: 'Castle queenside and attack.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p45',
    fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/2BNP3/2N1B3/PPP2PPP/R2QK2R w KQ - 0 8',
    moves: ['Qd2', 'a6', 'O-O-O'],
    rating: 1650,
    themes: ['opening', 'sicilian'],
    title: 'Dragon Setup',
    description: 'Set up the Yugoslav Attack.',
    difficulty: 'expert',
    xpReward: 60,
  },
  {
    id: 'p46',
    fen: '8/5pk1/8/8/8/8/5PP1/6K1 w - - 0 1',
    moves: ['f4', 'Kf6', 'Kf2'],
    rating: 1500,
    themes: ['endgame', 'kingActivity'],
    title: 'King Activity',
    description: 'Activate your king.',
    difficulty: 'expert',
    xpReward: 50,
  },
  {
    id: 'p47',
    fen: 'r1bq1rk1/pp1nppbp/2np2p1/8/2BNP3/2N1BP2/PPPQ2PP/R3K2R w KQ - 0 9',
    moves: ['O-O-O', 'a6', 'g4'],
    rating: 1700,
    themes: ['attack', 'pawnStorm'],
    title: 'Kingside Storm',
    description: 'Launch a pawn storm.',
    difficulty: 'expert',
    xpReward: 65,
  },
  {
    id: 'p48',
    fen: 'r1b2rk1/pp2ppbp/2np1np1/q7/2BNP3/2N1BP2/PPPQ2PP/R3K2R w KQ - 0 10',
    moves: ['O-O-O', 'Qc7', 'h4'],
    rating: 1750,
    themes: ['attack', 'sicilian'],
    title: 'Yugoslav Attack',
    description: 'Continue with precision.',
    difficulty: 'expert',
    xpReward: 70,
  },
  {
    id: 'p49',
    fen: 'r2qk2r/pp1nbppp/2p1pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQK2R w KQkq - 2 8',
    moves: ['Qc2', 'O-O', 'O-O'],
    rating: 1600,
    themes: ['opening', 'qgd'],
    title: 'QGD Classical',
    description: 'Navigate the Queens Gambit.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p50',
    fen: 'rnbqkb1r/pp2pppp/5n2/2pp4/2PP4/2N5/PP2PPPP/R1BQKBNR w KQkq d6 0 4',
    moves: ['cxd5', 'Nxd5', 'e4'],
    rating: 1650,
    themes: ['opening', 'panov'],
    title: 'Panov Attack',
    description: 'Play the aggressive Panov.',
    difficulty: 'expert',
    xpReward: 60,
  },
  {
    id: 'p51',
    fen: 'rnbqkb1r/pp2pppp/5n2/3p4/3P4/2N2N2/PPP1PPPP/R1BQKB1R w KQkq - 2 4',
    moves: ['Bg5', 'e6', 'e3'],
    rating: 1500,
    themes: ['opening', 'london'],
    title: 'London System',
    description: 'Set up the solid London.',
    difficulty: 'expert',
    xpReward: 50,
  },
  {
    id: 'p52',
    fen: 'rnbqkb1r/ppp1pppp/5n2/3p4/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3',
    moves: ['cxd5', 'Nxd5', 'e4'],
    rating: 1550,
    themes: ['opening', 'queensGambit'],
    title: 'Queens Gambit',
    description: 'Fight for the center.',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p53',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    moves: ['Bb5', 'a6', 'Ba4'],
    rating: 1700,
    themes: ['opening', 'ruyLopez'],
    title: 'Ruy Lopez',
    description: 'Play the classical Ruy Lopez.',
    difficulty: 'expert',
    xpReward: 65,
  },
  // === NEW PUZZLES (p54-p65) ===
  {
    id: 'p54',
    fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    moves: ['Re8#'],
    rating: 400,
    themes: ['mate', 'backRank'],
    title: 'Back Rank Mate',
    description: 'The king is stuck behind its own pawns. Deliver the final blow!',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p55',
    fen: 'r1bqkb1r/pppppppp/2n2n2/8/3NP3/8/PPP2PPP/RNBQKB1R w KQkq - 2 4',
    moves: ['Nxc6', 'bxc6'],
    rating: 450,
    themes: ['tactics', 'capture'],
    title: 'Simple Fork',
    description: 'Capture the knight and damage Black\'s pawn structure.',
    difficulty: 'easy',
    xpReward: 10,
  },
  {
    id: 'p56',
    fen: 'rnb1kbnr/pppppppp/8/8/4q3/2N5/PPPPPPPP/R1BQKBNR w KQkq - 0 1',
    moves: ['Nxe4'],
    rating: 500,
    themes: ['tactics', 'capture'],
    title: 'Queen Capture',
    description: 'Black\'s queen has wandered into danger. Win the queen!',
    difficulty: 'easy',
    xpReward: 15,
  },
  {
    id: 'p57',
    fen: '8/4P1k1/8/8/8/8/6K1/8 w - - 0 1',
    moves: ['e8=Q'],
    rating: 550,
    themes: ['endgame', 'promotion'],
    title: 'Pawn Promotion',
    description: 'Push the pawn to promotion and get a new queen!',
    difficulty: 'easy',
    xpReward: 15,
  },
  {
    id: 'p58',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4',
    moves: ['Nxe4', 'Bxf7+', 'Kf8'],
    rating: 750,
    themes: ['tactics', 'sacrifice', 'fork'],
    title: 'Knight Fork Royal',
    description: 'Win a pawn but watch out for the bishop counter-strike!',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p59',
    fen: 'r2qkbnr/ppp2ppp/2np4/4p3/2B1P1b1/5N2/PPPP1PPP/RNBQ1RK1 w kq - 2 5',
    moves: ['Bxf7+', 'Kd7'],
    rating: 800,
    themes: ['tactics', 'sacrifice', 'discoveredAttack'],
    title: 'Discovered Attack',
    description: 'Sacrifice the bishop to expose the enemy king!',
    difficulty: 'medium',
    xpReward: 25,
  },
  {
    id: 'p60',
    fen: 'rnbqk2r/pppp1ppp/4pn2/8/1bPP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 2 4',
    moves: ['Qb3', 'Bxc3+', 'bxc3'],
    rating: 900,
    themes: ['tactics', 'pin', 'strategy'],
    title: 'Pin and Win',
    description: 'Use the queen to exploit the pin on the knight!',
    difficulty: 'medium',
    xpReward: 30,
  },
  {
    id: 'p61',
    fen: 'r3k3/8/8/3N4/8/8/8/4K3 w - - 0 1',
    moves: ['Nc7+', 'Kd8', 'Nxa8'],
    rating: 950,
    themes: ['tactics', 'fork', 'endgame'],
    title: 'Knight Fork',
    description: 'Fork the king and rook with the knight!',
    difficulty: 'medium',
    xpReward: 30,
  },
  {
    id: 'p62',
    fen: 'r1bq1rk1/pppn1ppp/4pn2/3p4/1bPP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 8',
    moves: ['cxd5', 'exd5', 'Nxd5'],
    rating: 1200,
    themes: ['tactics', 'sacrifice', 'centerControl'],
    title: 'Greek Gift Sacrifice',
    description: 'Break open the center and win a pawn with a tactical sequence!',
    difficulty: 'hard',
    xpReward: 40,
  },
  {
    id: 'p63',
    fen: 'r1b2rk1/pp3ppp/2n1pn2/q2p4/3P4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 9',
    moves: ['Nb5', 'Qd8', 'Nc7'],
    rating: 1350,
    themes: ['tactics', 'fork', 'knightOutpost'],
    title: 'Knight Outpost',
    description: 'Drive the queen away and plant the knight deep in enemy territory!',
    difficulty: 'hard',
    xpReward: 45,
  },
  {
    id: 'p64',
    fen: 'r2q1rk1/ppp1bppp/2n1pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 8',
    moves: ['cxd5', 'exd5', 'Nxd5', 'Nxd5', 'Bxh7+'],
    rating: 1550,
    themes: ['sacrifice', 'tactics', 'attack'],
    title: 'Positional Sacrifice',
    description: 'Exchange pieces to open lines and launch a devastating bishop sacrifice!',
    difficulty: 'expert',
    xpReward: 55,
  },
  {
    id: 'p65',
    fen: 'r1bq1rk1/pp2bppp/2n1pn2/2pp4/2PP4/2N1PN2/PPB2PPP/R1BQ1RK1 w - - 0 8',
    moves: ['cxd5', 'exd5', 'dxc5', 'Bxc5', 'b4'],
    rating: 1700,
    themes: ['strategy', 'pawnStructure', 'opening'],
    title: 'Exchange Sacrifice',
    description: 'Open lines and gain a positional advantage with precise pawn play!',
    difficulty: 'expert',
    xpReward: 65,
  },
]

export const TRAPS: Trap[] = [
  {
    id: 'legal-trap',
    name: "Legal's Trap",
    opening: 'Italian Game',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'd6', 'Nc3', 'Bg4', 'h3', 'Bh5', 'Nxe5', 'Bxd1', 'Bxf7+', 'Ke7', 'Nd5#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A classic trap where White sacrifices the queen to deliver a stunning checkmate.',
    explanation: [
      'White plays Nxe5 seemingly losing the queen to Bxd1',
      'But after Bxf7+ the king is forced to e7',
      'Then Nd5# delivers a beautiful checkmate',
      'The knight on e5, bishop on f7, and knight on d5 create an inescapable net'
    ],
    moveAnnotations: [
      'Standard opening',
      'Black mirrors',
      'Develops and attacks e5',
      'Defends e5',
      'Targets f7',
      'Supports e5 passively',
      'Develops naturally',
      'Pins the knight — this is the mistake!',
      'Asks the bishop a question',
      'Maintains the pin... but falls into the trap',
      'Sacrifice! Seemingly hangs the queen',
      'Black greedily takes the queen',
      'Check! The king must move',
      'Forced — only legal move',
      'Checkmate! The knights and bishop create a net',
    ],
    difficulty: 'beginner',
    side: 'white',
    xpReward: 30,
  },
  {
    id: 'stafford-gambit',
    name: 'Stafford Gambit',
    opening: 'Petrov Defense',
    moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'Nc6', 'Nxc6', 'dxc6', 'd3', 'Bc5', 'Bg5', 'Nxe4', 'Bxd8', 'Bxf2+', 'Ke2', 'Bg4#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A trappy gambit where Black sacrifices a pawn for a vicious attack.',
    explanation: [
      'Black plays Nc6 instead of the normal dxc6, offering a piece',
      'After dxc6, Black develops rapidly with Bc5 and sets up tactics',
      'The key idea is Bxf2+ forcing the king to e2',
      'Then Bg4# is a stunning checkmate'
    ],
    moveAnnotations: [
      'Standard opening',
      'Mirrors',
      'Attacks e5',
      'The Petrov — counter-attacks e4',
      'Takes the pawn',
      'The Stafford Gambit! Offering the knight',
      'White takes the bait',
      'Opens the d-file',
      'Tries to solidify',
      'Aims at f2 — the attack begins',
      'Tries to pin, but it\'s too late...',
      'Attacks the queen with tempo',
      'Takes the queen, thinking it\'s winning',
      'Check! Drags the king out',
      'Forced',
      'Checkmate! Beautiful bishop coordination',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'fried-liver',
    name: 'Fried Liver Attack',
    opening: 'Italian Game - Two Knights',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5', 'd5', 'exd5', 'Nxd5', 'Nxf7', 'Kxf7', 'Qf3+', 'Ke6', 'Nc3'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A devastating attack where White sacrifices a knight on f7 to drag the Black king into the center.',
    explanation: [
      'White plays the aggressive Ng5 targeting f7',
      'After d5 exd5 Nxd5, White strikes with Nxf7!',
      'The king is forced to take and enters a danger zone',
      'Qf3+ followed by Nc3 creates an overwhelming attack'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Italian Game setup',
      'Two Knights Defense',
      'The attack begins! Threatens Nxf7',
      'Black tries to counter in the center',
      'Captures',
      'Seems safe... but falls into the Fried Liver',
      'Knight sacrifice! Exposing the king',
      'Must accept',
      'Check! The king is dragged forward',
      'Walking into the fire',
      'Develops with tempo — devastating attack',
    ],
    difficulty: 'beginner',
    side: 'white',
    xpReward: 30,
  },
  {
    id: 'elephant-trap',
    name: 'Elephant Trap',
    opening: "Queen's Gambit Declined",
    moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Nbd7', 'cxd5', 'exd5', 'Nxd5', 'Nxd5', 'Bxd8', 'Bb4+', 'Qd2', 'Bxd2+', 'Kxd2', 'Kxd8'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A classic trap where Black wins material after White greedily captures the d5 pawn.',
    explanation: [
      'White plays cxd5 exd5, then greedily takes Nxd5',
      'Black responds Nxd5, and after Bxd8, plays the shocking Bb4+!',
      'White must block with Qd2, then Bxd2+ Kxd2 Kxd8',
      'Black has won a full piece!'
    ],
    moveAnnotations: [
      'Queen\'s pawn opening',
      'Symmetrical center',
      'The Queen\'s Gambit',
      'Declines',
      'Develops',
      'Develops',
      'Pins the knight',
      'Sets the trap — looks passive but...',
      'White exchanges',
      'Recaptures',
      'Greedy! This springs the trap',
      'Counter-capture',
      'Takes the queen — but...',
      'Surprise check! The real point',
      'Only move to block',
      'Takes with check again',
      'Forced recapture',
      'Black takes the bishop — net material gain!',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'lasker-trap',
    name: 'Lasker Trap',
    opening: "Queen's Gambit Accepted",
    moves: ['d4', 'd5', 'c4', 'dxc4', 'e3', 'b5', 'a4', 'c6', 'axb5', 'cxb5', 'Qf3'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'Named after Emanuel Lasker, this trap features sharp queenside play.',
    explanation: [
      'Black plays the tricky b5 trying to hold the c4 pawn',
      'White attacks with a4, and after the exchanges, plays Qf3',
      'This creates double threats on c6 and the a8 rook',
      'The key lesson is understanding pawn tension in the QGA'
    ],
    moveAnnotations: [
      'Queen\'s pawn',
      'Center control',
      'Queen\'s Gambit',
      'Accepts the gambit',
      'Plans to recapture the pawn',
      'Tricky! Holds onto the extra pawn',
      'Attacks the pawn chain',
      'Reinforces b5',
      'Captures',
      'Recaptures',
      'Forks the rook on a8 and threatens mate ideas',
    ],
    difficulty: 'intermediate',
    side: 'white',
    xpReward: 35,
  },
  {
    id: 'magnus-smith-trap',
    name: 'Magnus Smith Trap',
    opening: 'Sicilian Defense',
    moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'Nc6', 'Bc4', 'g6', 'Nxc6', 'bxc6', 'e5'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A sneaky trap in the Sicilian where White wins material with a powerful central thrust.',
    explanation: [
      'White develops naturally with Bc4 then plays the strong e5!',
      'This move attacks the d6 pawn and the f6 knight',
      'Black is forced into an awkward position',
      'White gains significant advantage'
    ],
    moveAnnotations: [
      'Standard',
      'Sicilian Defense',
      'Develops',
      'Supports e5',
      'Opens the center',
      'Exchanges',
      'Recaptures centrally',
      'Develops',
      'Develops',
      'Develops — but this allows the trap',
      'Targets f7',
      'Prepares fianchetto... but weakens',
      'Exchanges first',
      'Forced recapture',
      'The trap springs! Wins the d6 pawn or the knight',
    ],
    difficulty: 'advanced',
    side: 'white',
    xpReward: 50,
  },
  {
    id: 'blackburne-shilling',
    name: 'Blackburne Shilling Gambit',
    opening: 'Italian Game',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nd4', 'Nxe5', 'Qg5', 'Nxf7', 'Qxg2', 'Rf1', 'Qxe4+', 'Be2', 'Nf3#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A dangerous trap where Black sacrifices material for a smothered mate.',
    explanation: [
      'Black plays the unusual Nd4, seemingly a mistake',
      'If White takes on f7, Black plays Qg5 with threats',
      'After Qxg2 Rf1, Qxe4+ sets up the finale',
      'Nf3# is a beautiful smothered mate!'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Italian Game',
      'Unusual! Looks like a mistake',
      'Takes the free pawn — falling in!',
      'Attacks both the knight and g2',
      'Tries to counter-attack',
      'Takes the pawn with threats',
      'Defends f2',
      'Check! Forces the block',
      'Only move',
      'Smothered mate! Beautiful finish',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 45,
  },
  {
    id: 'englund-gambit',
    name: 'Englund Gambit Trap',
    opening: 'Englund Gambit',
    moves: ['d4', 'e5', 'dxe5', 'Nc6', 'Nf3', 'Qe7', 'Bf4', 'Qb4+', 'Bd2', 'Qxb2', 'Bc3', 'Bb4', 'Qd2', 'Bxc3', 'Qxc3', 'Qc1#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A surprise gambit where Black gives up material for a back rank mate.',
    explanation: [
      'Black gambits a pawn with e5 to create tactical chaos',
      'The key is Qb4+ forcing Bd2, then Qxb2 grabs a pawn',
      'After the sequence Bc3 Bb4, Black infiltrates',
      'Qc1# delivers checkmate on the back rank!'
    ],
    moveAnnotations: [
      'Standard',
      'The Englund Gambit — surprising!',
      'Takes the free pawn',
      'Develops with pressure',
      'Natural development',
      'Attacks the pawn and prepares tricks',
      'Defends e5',
      'Check! Forces a decision',
      'Blocks the check',
      'Grabs the b-pawn',
      'Tries to trap the queen',
      'Counter-pin!',
      'Tries to hold',
      'Takes the bishop',
      'Recaptures',
      'Back rank mate! Queen infiltrates',
    ],
    difficulty: 'intermediate',
    side: 'black',
    xpReward: 40,
  },
  {
    id: 'fishing-pole',
    name: 'Fishing Pole Trap',
    opening: 'Ruy Lopez',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6', 'O-O', 'Ng4', 'h3', 'h5', 'hxg4', 'hxg4', 'Ne1', 'Qh4', 'f4', 'g3', 'fxe5', 'Qh1#'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'A tricky trap in the Ruy Lopez where Black sacrifices a knight for a mating attack.',
    explanation: [
      'Black plays Ng4 offering the knight as bait',
      'If White takes hxg4 hxg4, the h-file opens dangerously',
      'Black follows with Qh4 creating threats',
      'The final Qh1# is unstoppable!'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Ruy Lopez',
      'Develops',
      'Castles',
      'The Fishing Pole! Offers the knight',
      'Attacks the knight',
      'Offers a piece sacrifice!',
      'Takes the bait',
      'Opens the h-file — deadly!',
      'Tries to retreat',
      'Queen joins the attack via the open file',
      'Tries to block',
      'Pawn advances with tempo',
      'Takes',
      'Checkmate on h1! The h-file is lethal',
    ],
    difficulty: 'advanced',
    side: 'black',
    xpReward: 50,
  },
  {
    id: 'noahs-ark',
    name: "Noah's Ark Trap",
    opening: 'Ruy Lopez',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'd6', 'd4', 'b5', 'Bb3', 'Nxd4', 'Nxd4', 'exd4', 'Qxd4', 'c5', 'Qd5', 'Be6', 'Qc6+', 'Bd7', 'Qd5', 'c4'],
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'An ancient trap where Black traps the White bishop on b3.',
    explanation: [
      'Black plays b5 and a6 to push the bishop back',
      'After the central exchanges, Black plays c5-c4',
      'The bishop on b3 is completely trapped',
      'This trap has been known since the 16th century!'
    ],
    moveAnnotations: [
      'Standard',
      'Standard',
      'Develops',
      'Develops',
      'Ruy Lopez',
      'Morphy Defense',
      'Retreats',
      'Supports e5',
      'Opens the center',
      'Pushes the bishop further back',
      'Retreats again',
      'Captures the center pawn',
      'Recaptures',
      'Takes back',
      'Takes with the queen',
      'Attacks the queen and starts the trap',
      'Queen retreats',
      'Attacks the queen again',
      'Check — trying to escape',
      'Blocks',
      'Back again',
      'The bishop is trapped! Nowhere to go',
    ],
    difficulty: 'beginner',
    side: 'black',
    xpReward: 30,
  },
]

export const AI_LEVELS = [
  { level: 1, name: 'Beginner Bot', rating: 400, description: 'Makes random moves, perfect for learning', depth: 1, icon: 'P', color: '#4ade80' },
  { level: 2, name: 'Casual Player', rating: 600, description: 'Knows basic tactics but misses a lot', depth: 2, icon: 'P', color: '#4ade80' },
  { level: 3, name: 'Club Player', rating: 800, description: 'Understands basic strategy and openings', depth: 3, icon: 'N', color: '#60a5fa' },
  { level: 4, name: 'Tournament Player', rating: 1000, description: 'Solid player with good tactical vision', depth: 5, icon: 'N', color: '#60a5fa' },
  { level: 5, name: 'Expert', rating: 1200, description: 'Strong player who rarely blunders', depth: 7, icon: 'B', color: '#a78bfa' },
  { level: 6, name: 'Master', rating: 1400, description: 'Plays at a master level with deep calculation', depth: 9, icon: 'R', color: '#f59e0b' },
  { level: 7, name: 'Grandmaster', rating: 1600, description: 'Near-perfect play with devastating attacks', depth: 12, icon: 'Q', color: '#f59e0b' },
  { level: 8, name: 'Stockfish Beast', rating: 2000, description: 'Maximum engine strength. Good luck!', depth: 15, icon: 'K', color: '#ef4444' },
]

export const PUZZLE_THEMES = [
  'All Puzzles',
  'Checkmate',
  'Tactics',
  'Forks',
  'Pins',
  'Back Rank',
  'Sacrifice',
  'Endgame',
  'Strategy',
]

export function getDifficultyColor(difficulty: string): string {
  switch (difficulty) {
    case 'beginner':
    case 'easy':
      return 'text-green-400'
    case 'intermediate':
    case 'medium':
      return 'text-yellow-400'
    case 'advanced':
    case 'hard':
      return 'text-orange-400'
    case 'expert':
      return 'text-red-400'
    default:
      return 'text-muted-foreground'
  }
}

export function getDifficultyBg(difficulty: string): string {
  switch (difficulty) {
    case 'beginner':
    case 'easy':
      return 'bg-green-400/10 text-green-400 border-green-400/20'
    case 'intermediate':
    case 'medium':
      return 'bg-yellow-400/10 text-yellow-400 border-yellow-400/20'
    case 'advanced':
    case 'hard':
      return 'bg-orange-400/10 text-orange-400 border-orange-400/20'
    case 'expert':
      return 'bg-red-400/10 text-red-400 border-red-400/20'
    default:
      return 'bg-muted text-muted-foreground border-border'
  }
}

export function getRarityColor(rarity: string): string {
  switch (rarity) {
    case 'common':
      return 'text-gray-400 border-gray-400/20'
    case 'rare':
      return 'text-blue-400 border-blue-400/30'
    case 'epic':
      return 'text-purple-400 border-purple-400/30'
    case 'legendary':
      return 'text-yellow-400 border-yellow-400/30'
    default:
      return 'text-muted-foreground border-border'
  }
}
